-- Emoji Drops — shared marketplace + real Live Drops v1.
-- Run this migration in the Supabase SQL editor after supabase/schema.sql.

create table if not exists public.market_listings (
  id uuid primary key default public.gen_random_uuid(),
  seller_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  emoji text not null,
  rarity text not null check (rarity in ('common','rare','epic','mythical','legendary')),
  case_id text,
  item_price numeric(12,2) not null check (item_price > 0),
  listing_price numeric(12,2) not null check (listing_price > 0),
  status text not null default 'active' check (status in ('active','sold','cancelled')),
  buyer_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  sold_at timestamptz
);
create index if not exists market_active_type_price_idx on public.market_listings (rarity, emoji, listing_price, created_at) where status='active';
create index if not exists market_active_case_price_idx on public.market_listings (case_id, rarity, listing_price, created_at) where status='active';
create index if not exists market_seller_status_idx on public.market_listings (seller_id, status, created_at desc);
alter table public.market_listings enable row level security;
drop policy if exists "market_active_public_read" on public.market_listings;
create policy "market_active_public_read" on public.market_listings for select using (status='active');
drop policy if exists "market_own_history_read" on public.market_listings;
create policy "market_own_history_read" on public.market_listings for select using (auth.uid()=seller_id or auth.uid()=buyer_id);

create table if not exists public.live_drops (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null default 'Player',
  item jsonb not null,
  case_id text,
  item_price numeric(12,2) not null default 0 check (item_price >= 0),
  created_at timestamptz not null default now()
);
create index if not exists live_drops_created_idx on public.live_drops (created_at desc);
alter table public.live_drops enable row level security;
drop policy if exists "live_drops_public_read" on public.live_drops;
create policy "live_drops_public_read" on public.live_drops for select using (created_at > now() - interval '30 minutes');

create or replace function public.create_market_listing(p_item_id text, p_price numeric) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); inv jsonb; item jsonb; clean numeric; listing jsonb;
begin
 if uid is null then raise exception 'AUTH_REQUIRED'; end if;
 clean:=round(coalesce(p_price,0),2);
 if clean<=0 or clean>100000000 then raise exception 'INVALID_LISTING_PRICE'; end if;
 select inventory into inv from public.profiles where id=uid for update;
 if inv is null then raise exception 'PROFILE_NOT_FOUND'; end if;
 select x into item from jsonb_array_elements(coalesce(inv,'[]'::jsonb)) x where x->>'id'=p_item_id limit 1;
 if item is null then raise exception 'ITEM_NOT_FOUND'; end if;
 if coalesce((item->>'price')::numeric,0)<=0 then raise exception 'INVALID_ITEM_PRICE'; end if;
 insert into public.market_listings(seller_id,item_id,emoji,rarity,case_id,item_price,listing_price)
 values(uid,p_item_id,coalesce(item->>'emoji','🎁'),coalesce(item->>'rarity','common'),item->>'case_id',coalesce((item->>'price')::numeric,0),clean)
 returning jsonb_build_object('id',id,'item_id',item_id,'emoji',emoji,'rarity',rarity,'case_id',case_id,'item_price',item_price,'listing_price',listing_price,'status',status,'created_at',created_at) into listing;
 update public.profiles set inventory=(select coalesce(jsonb_agg(x),'[]'::jsonb) from jsonb_array_elements(inv) x where x->>'id'<>p_item_id),updated_at=now() where id=uid;
 return listing;
end; $$;

create or replace function public.cancel_market_listing(p_listing_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); l public.market_listings%rowtype; inv jsonb; restored jsonb;
begin
 if uid is null then raise exception 'AUTH_REQUIRED'; end if;
 select * into l from public.market_listings where id=p_listing_id for update;
 if not found then raise exception 'LISTING_NOT_FOUND'; end if;
 if l.seller_id<>uid then raise exception 'NOT_OWNER'; end if;
 if l.status<>'active' then raise exception 'LISTING_NOT_ACTIVE'; end if;
 select inventory into inv from public.profiles where id=uid for update;
 restored:=jsonb_build_object('id',l.item_id,'emoji',l.emoji,'rarity',l.rarity,'case_id',l.case_id,'price',l.item_price,'listed_at',l.created_at);
 update public.profiles set inventory=coalesce(inv,'[]'::jsonb)||jsonb_build_array(restored),updated_at=now() where id=uid;
 update public.market_listings set status='cancelled' where id=p_listing_id;
 return jsonb_build_object('listing_id',p_listing_id,'item',restored);
end; $$;

-- Purchase reconstructs the listed item from the locked listing row.
-- The seller's inventory no longer contains the item because create_market_listing removes it atomically.
create or replace function public.buy_market_listing(p_listing_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare buyer uuid:=auth.uid(); l public.market_listings%rowtype; buyer_bal numeric; buyer_inv jsonb; item jsonb;
begin
 if buyer is null then raise exception 'AUTH_REQUIRED'; end if;
 select * into l from public.market_listings where id=p_listing_id and status='active' for update;
 if not found then raise exception 'LISTING_NOT_FOUND'; end if;
 if l.seller_id=buyer then raise exception 'SELF_PURCHASE'; end if;
 -- Lock both profiles in deterministic UUID order to prevent cross-purchase deadlocks.
 if buyer < l.seller_id then
   perform 1 from public.profiles where id=buyer for update;
   perform 1 from public.profiles where id=l.seller_id for update;
 else
   perform 1 from public.profiles where id=l.seller_id for update;
   perform 1 from public.profiles where id=buyer for update;
 end if;
 select balance,inventory into buyer_bal,buyer_inv from public.profiles where id=buyer;
 if buyer_bal is null then raise exception 'PROFILE_NOT_FOUND'; end if;
 if buyer_bal<l.listing_price then raise exception 'INSUFFICIENT_FUNDS'; end if;
 item:=jsonb_build_object('id',l.item_id,'emoji',l.emoji,'rarity',l.rarity,'case_id',l.case_id,'price',l.item_price,'created_at',l.created_at);
 update public.profiles set balance=buyer_bal-l.listing_price,inventory=coalesce(buyer_inv,'[]'::jsonb)||jsonb_build_array(item),updated_at=now() where id=buyer;
 update public.profiles set balance=balance+l.listing_price,updated_at=now() where id=l.seller_id;
 update public.market_listings set status='sold',buyer_id=buyer,sold_at=now() where id=l.id;
 return jsonb_build_object('listing_id',l.id,'item',item,'price',l.listing_price,'balance',buyer_bal-l.listing_price);
end; $$;

revoke execute on function public.create_market_listing(text,numeric) from public,anon;
revoke execute on function public.cancel_market_listing(uuid) from public,anon;
revoke execute on function public.buy_market_listing(uuid) from public,anon;
revoke execute on function public.market_snapshot() from public,anon;

grant execute on function public.create_market_listing(text,numeric) to authenticated;
grant execute on function public.cancel_market_listing(uuid) to authenticated;
grant execute on function public.buy_market_listing(uuid) to authenticated;

create or replace function public.market_snapshot() returns table(
 id uuid,seller_id uuid,item_id text,emoji text,rarity text,case_id text,item_price numeric,listing_price numeric,created_at timestamptz,nickname text
) language sql security definer set search_path='' as $$
 select l.id,l.seller_id,l.item_id,l.emoji,l.rarity,l.case_id,l.item_price,l.listing_price,l.created_at,coalesce(p.nickname,'Player')
 from public.market_listings l left join public.profiles p on p.id=l.seller_id
 where l.status='active' order by l.listing_price asc,l.created_at asc limit 200;
$$;

grant execute on function public.market_snapshot() to anon,authenticated;
grant select on public.live_drops to anon,authenticated;

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='live_drops') then
    alter publication supabase_realtime add table public.live_drops;
  end if;
end $$;

-- Case opening remains owned by the canonical open_case_server migration. This migration only owns Market and Live Drops storage/RPCs; it must not override the case transaction.
