(()=>{'use strict';
/* Statistical QA for the client economy. Read-only: never mutates catalog or user state. */
const W={common:55,rare:27,epic:12,mythical:5,legendary:1};
const value=x=>Number(x?.value)||Number(x?.price)||Number(String(x?.value||x?.price||0).replace(/[^0-9.]/g,''))||0;
function pools(list){const p={};for(const r of Object.keys(W))p[r]=list.filter(x=>x?.rarity===r);return p}
const weightedExpected=list=>{let ev=0;const p=pools(list);for(const [r,w] of Object.entries(W)){const pool=p[r],avg=pool.length?pool.reduce((s,x)=>s+value(x),0)/pool.length:0;ev+=(w/100)*avg}return ev};
function pick(list,p){let q=Math.random()*100,n=0;for(const [r,w] of Object.entries(W)){n+=w;if(q<n){const pool=p[r];return pool.length?pool[Math.floor(Math.random()*pool.length)]:null}}return null}
function chance(base,target,mult){if(!(base>0&&target>base&&mult>1))return 0;const raw=((base*mult-target)/(base*mult-base))*100;const evSafe=(base/target)*90.8;return Math.max(0,Math.min(100,raw,evSafe))}
function simulateCase(list,cost,runs=12000){let total=0,count=0;const rarity={common:0,rare:0,epic:0,mythical:0,legendary:0},p=pools(list);for(let i=0;i<runs;i++){const x=pick(list,p);if(!x)continue;count++;total+=value(x);rarity[x.rarity]=(rarity[x.rarity]||0)+1}const theoreticalEv=weightedExpected(list);return{runs,count,ev:count?total/count:0,rtp:cost?total/(count*cost):0,rarity,theoreticalEv,theoreticalRtp:cost?theoreticalEv/cost:0}}
function simulateUpgrade(list){const vals=[...new Set(list.map(value).filter(v=>v>0))].sort((a,b)=>a-b);let attempts=0,maxRatio=0,maxNet=0,worstChance=100,best=null;for(const base of vals.slice(0,160)){for(const mult of [1.5,2,3,5]){for(const target of vals){if(target<=base||target>base*mult)continue;const p=chance(base,target,mult)/100,ev=target*p,net=ev-base,ratio=ev/base;attempts++;if(ratio>maxRatio){maxRatio=ratio;maxNet=net;best={base,target,mult,chance:p*100,ev,net,ratio}}worstChance=Math.min(worstChance,p*100)}}}return{attempts,maxRatio,maxNet,worstChance,best,profitable:maxNet>0.000001}}
function run(){if(typeof cases==='undefined'||typeof casePrices==='undefined')return;const allItems=Object.values(cases).flat(),report={version:5,at:new Date().toISOString(),cases:{},global:{items:allItems.length,upgrade:simulateUpgrade(allItems)},errors:[]};for(const [key,list] of Object.entries(cases)){const cost=Number(casePrices[key])||0,s=simulateCase(list,cost),u=report.global.upgrade;report.cases[key]={cost,items:list.length,simulation:s};if(!cost)report.errors.push(`${key}: missing price`);if(!list.length)report.errors.push(`${key}: empty catalog`);for(const r of Object.keys(W))if(!list.some(x=>x?.rarity===r))report.errors.push(`${key}: missing rarity ${r}`);if(s.theoreticalRtp<0.82||s.theoreticalRtp>0.99)report.errors.push(`${key}: theoretical RTP ${(s.theoreticalRtp*100).toFixed(2)}% outside 82-99% QA band`);if(Math.abs(s.rtp-s.theoreticalRtp)>0.06)report.errors.push(`${key}: sampled RTP drift ${(Math.abs(s.rtp-s.theoreticalRtp)*100).toFixed(2)}pp`)}if(report.global.upgrade.profitable)report.errors.push(`global: upgrade positive EV detected (${(report.global.upgrade.maxRatio*100).toFixed(2)}% of source value)`);window.__emojiDropsEconomyQA=report;console.info('[Emoji Drops] economy QA',report)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,0),{once:true});else setTimeout(run,0);
})();
