(()=>{'use strict';
const T={common:.442,rare:.796,epic:1.326,mythical:2.653,legendary:5.31};
const W={common:55,rare:27,epic:12,mythical:5,legendary:1};
const fmt=n=>Math.round(n)+'₽';
const val=x=>Number(x?.value)||Number(x?.price)||Number(String(x?.value||x?.price||0).replace(/[^0-9.\-]/g,''))||0;
function balance(){if(typeof cases==='undefined'||typeof casePrices==='undefined')return;Object.entries(cases).forEach(([key,list])=>{const cost=Number(casePrices[key])||0;Object.entries(T).forEach(([rarity,mult])=>{const group=list.filter(x=>x?.rarity===rarity);if(!group.length)return;const sorted=[...group].sort((a,b)=>val(a)-val(b));sorted.forEach((item,i)=>{const t=sorted.length===1?1:(.85+.30*(i/(sorted.length-1)));const v=Math.max(1,Math.round(cost*mult*t));item.value=v;item.price=fmt(v);item.caseKey=key})})});window.__emojiDropsEconomy={version:3,targetRTP:.908,weights:{...W},multipliers:{...T}}}
function decoratePreview(){const modal=document.getElementById('edOpenModal');if(!modal||typeof cases==='undefined')return;const items=modal.querySelectorAll('.preview-item');if(!items.length)return;const title=(modal.querySelector('.panel-head h2')?.textContent||'').split(' · ')[0].trim().toLowerCase();const key=Object.keys(cases).find(k=>k.toLowerCase()===title);if(!key)return;const list=cases[key]||[],counts={};list.forEach(x=>counts[x.rarity]=(counts[x.rarity]||0)+1);items.forEach((el,i)=>{const it=list[i];if(!it)return;const p=(W[it.rarity]||0)/(counts[it.rarity]||1);let small=el.querySelector('small');if(!small){small=document.createElement('small');el.appendChild(small)}small.textContent=`${fmt(val(it))} · ${p.toFixed(2)}%`})}
function boot(){balance();document.addEventListener('click',e=>{if(e.target.closest('[data-ed-case]'))setTimeout(decoratePreview,0)},true);setTimeout(decoratePreview,80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();