(()=>{'use strict';
const T={common:.50,rare:.90,epic:1.50,mythical:3.00,legendary:6.00};
const W={common:55,rare:27,epic:12,mythical:5,legendary:1};
const ICON={smile:'😀',moves:'🕺',nature:'🌿',food:'🍔',animals:'🐶',transport:'🚗',sport:'⚽',games:'🎮'};
const fmt=n=>Math.round(n)+'₽';
const val=x=>Number(x?.value)||Number(x?.price)||Number(String(x?.value||x?.price||0).replace(/[^0-9.]/g,''))||0;
function balance(){if(typeof cases==='undefined'||typeof casePrices==='undefined')return;Object.entries(cases).forEach(([key,list])=>{const cost=Number(casePrices[key])||0;Object.entries(T).forEach(([rarity,mult])=>{const group=list.filter(x=>x?.rarity===rarity);if(!group.length)return;const sorted=[...group].sort((a,b)=>val(a)-val(b));sorted.forEach((item,i)=>{const t=sorted.length===1?1:(.85+.30*(i/(sorted.length-1)));const v=Math.max(1,Math.round(cost*mult*t));item.value=v;item.price=fmt(v);item.caseKey=key})})});window.__emojiDropsEconomy={version:1,targetRTP:.908,weights:{...W},multipliers:{...T}}}
function rebuildCases(){const g=document.getElementById('cases');if(!g||typeof cases==='undefined'||typeof casePrices==='undefined')return;const frag=document.createDocumentFragment();Object.keys(cases).forEach(k=>{const tile=document.createElement('div');tile.className='case-tile';const card=document.createElement('button');card.type='button';card.className='case-card';card.dataset.edCase=k;const items=cases[k]||[];const cost=Number(casePrices[k])||0;card.innerHTML=`<div class="case-art">${ICON[k]||'📦'}</div><div class="case-info"><div class="case-meta">${items.length} предметов</div><div class="case-name">${k[0].toUpperCase()+k.slice(1)}</div><div class="case-price"><span>${fmt(cost)}</span></div></div>`;tile.appendChild(card);frag.appendChild(tile)});g.replaceChildren(frag)}
function decoratePreview(){const modal=document.getElementById('edOpenModal');if(!modal||typeof cases==='undefined')return;const items=modal.querySelectorAll('.preview-item');if(!items.length)return;const caseName=(modal.querySelector('.panel-head h2')?.textContent||'').split(' · ')[0].trim().toLowerCase();const key=Object.keys(cases).find(k=>k.toLowerCase()===caseName);if(!key)return;const list=cases[key]||[],counts={};list.forEach(x=>counts[x.rarity]=(counts[x.rarity]||0)+1);items.forEach((el,i)=>{const it=list[i];if(!it)return;const p=(W[it.rarity]||0)/(counts[it.rarity]||1);let small=el.querySelector('small');if(!small){small=document.createElement('small');el.appendChild(small)}small.innerHTML=`${fmt(val(it))} · ${p.toFixed(2)}%`})}
function boot(){balance();rebuildCases();document.addEventListener('click',e=>{if(e.target.closest('[data-ed-case]'))setTimeout(decoratePreview,0)},true);setTimeout(decoratePreview,50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
