(()=>{'use strict';
const PRICE={transport:25,animals:40,food:60,nature:85,moves:110,smile:140,sport:180,games:230,space:290,ocean:360,flags:420};
const NAME={transport:'Транспорт',animals:'Животные',food:'Еда',nature:'Природа',moves:'Движения',smile:'Улыбки',sport:'Спорт',games:'Игры',space:'Космос',ocean:'Океан',flags:'Флаги'};
const ICON={transport:'🚗',animals:'🐶',food:'🍔',nature:'🌿',moves:'🕺',smile:'😀',sport:'⚽',games:'🎮',space:'🌌',ocean:'🌊',flags:'🌍'};
const RANK=['common','common','common','common','common','common','common','common','common','common','common','common','common','common','rare','rare','rare','rare','rare','rare','rare','rare','rare','epic','epic','epic','epic','epic','epic','mythical','mythical','mythical','mythical','legendary','legendary'];
const POOL={space:['🌌','🪐','🌙','⭐','🌠','☄️','🛰️','🔭','🚀','🛸','👾','🌟','✨','💫','🌍','🌎','🌏','🌑','🌒','🌓','🌔','🌖','🌗','🌘','🌕','👽','🛰️','☄️','🚀','🌌','💫','🌟','🪐','🌠'],ocean:['🌊','🐚','🪸','🐠','🐟','🦀','🦐','🐡','🐬','🦑','🪼','🐙','🦞','🐢','🦈','🐳','🐋','⚓','🏝️','🤿','🔱','🧜','🧜‍♂️','🧜‍♀️','🫧','🪸','🐠','🐬','🦑','🐙','🦈','🐳','🔱','🪼']};
const MULT={common:.28,rare:.62,epic:1.18,mythical:2.35,legendary:4.8};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function build(key){const pool=POOL[key];if(!pool)return;cases[key]=pool.map((emoji,i)=>({emoji,rarity:RANK[i],caseId:key}));}
function setValues(){Object.entries(PRICE).forEach(([key,base])=>{casePrices[key]=base;const arr=cases[key];if(!Array.isArray(arr))return;arr.forEach((it,i)=>{const m=MULT[it.rarity]||MULT.common;const jitter=.92+(i%5)*.02;it.value=Math.max(1,Math.round(base*m*jitter));it.price=it.value+'₽';it.caseId=key})})}
function card(key){const t=document.createElement('div');t.className='case-tile';t.innerHTML=`<button type="button" class="case-card" data-case="${key}"><div class="case-art">${ICON[key]}</div><div class="case-info"><div class="case-meta">${cases[key].length} предметов</div><div class="case-name">${NAME[key]}</div><div class="case-price"><span>${PRICE[key]}₽</span></div></div></button>`;return t}
function render(){const g=$('#cases');if(!g)return;['space','ocean'].forEach(k=>g.querySelector(`[data-case="${k}"]`)?.closest('.case-tile')?.remove());const order=Object.keys(PRICE);order.forEach(k=>{if(!cases[k])return;const existing=g.querySelector(`[data-case="${k}"]`)?.closest('.case-tile');if(existing)return;const tile=card(k),nodes=[...g.querySelectorAll('.case-tile')],idx=order.indexOf(k),before=nodes.find(n=>order.indexOf(n.querySelector('[data-case]')?.dataset.case)>=idx);before?g.insertBefore(tile,before):g.appendChild(tile)});$$('.case-card',g).forEach(b=>{const k=b.dataset.case;if(!NAME[k])return;$('.case-name',b).textContent=NAME[k];$('.case-meta',b).textContent=(cases[k]||[]).length+' предметов';const p=$('.case-price span',b);if(p)p.textContent=PRICE[k]+'₽'})}
function apply(){try{build('space');build('ocean');setValues();render();document.documentElement.dataset.economy='v2'}catch(e){console.error('Emoji Drops economy:',e)}}
function boot(){apply();if(typeof window.renderAll==='function'&&!window.__edEconomyRenderPatched){const old=window.renderAll;window.__edEconomyRenderPatched=true;window.renderAll=function(){old();apply()}}setTimeout(apply,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();