(()=>{'use strict';
/* Deterministic-ish statistical QA for the client economy. It never mutates catalog or user state. */
const W={common:55,rare:27,epic:12,mythical:5,legendary:1};
const value=x=>Number(x?.value)||Number(x?.price)||Number(String(x?.value||x?.price||0).replace(/[^0-9.]/g,''))||0;
function pick(list){let q=Math.random()*100,n=0;for(const [r,w] of Object.entries(W)){n+=w;if(q<n){const pool=list.filter(x=>x?.rarity===r);return pool.length?pool[Math.floor(Math.random()*pool.length)]:null}}return null}
function simulateCase(list,cost,runs=12000){let total=0,count=0;const rarity={common:0,rare:0,epic:0,mythical:0,legendary:0};for(let i=0;i<runs;i++){const x=pick(list);if(!x)continue;count++;total+=value(x);rarity[x.rarity]=(rarity[x.rarity]||0)+1}return{runs,count,ev:count?total/count:0,rtp:cost?total/(count*cost):0,rarity}}
function simulateUpgrade(list){const vals=list.map(value).filter(v=>v>0);if(!vals.length)return{targets:0,avgGain:0};let gains=0,attempts=0;for(const base of vals.slice(0,Math.min(vals.length,80))){for(const mult of [1.5,2,3,5]){const targets=vals.filter(v=>v>base&&v<=base*mult);if(!targets.length)continue;const target=targets[Math.floor(targets.length/2)];const chance=Math.max(0,Math.min(100,((base*mult-target)/(base*mult-base))*100));gains+=target*chance/100-base;attempts++}}return{targets:attempts,avgGain:attempts?gains/attempts:0}}
function run(){if(typeof cases==='undefined'||typeof casePrices==='undefined')return;const report={version:1,at:new Date().toISOString(),cases:{},errors:[]};for(const [key,list] of Object.entries(cases)){const cost=Number(casePrices[key])||0;const s=simulateCase(list,cost);const u=simulateUpgrade(list);report.cases[key]={cost,items:list.length,simulation:s,upgrade:u};if(!cost)report.errors.push(`${key}: missing price`);if(!list.length)report.errors.push(`${key}: empty catalog`);for(const r of Object.keys(W))if(!list.some(x=>x?.rarity===r))report.errors.push(`${key}: missing rarity ${r}`);if(s.rtp<0.82||s.rtp>0.99)report.errors.push(`${key}: RTP ${(s.rtp*100).toFixed(2)}% outside 82-99% QA band`)}window.__emojiDropsEconomyQA=report;console.info('[Emoji Drops] economy QA',report)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,0),{once:true});else setTimeout(run,0);
})();
