(()=>{'use strict';
/* Statistical QA for the client economy. Read-only: never mutates catalog or user state. */
const W={common:55,rare:27,epic:12,mythical:5,legendary:1};
const value=x=>Number(x?.value)||Number(x?.price)||Number(String(x?.value||x?.price||0).replace(/[^0-9.]/g,''))||0;
function pick(list){let q=Math.random()*100,n=0;for(const [r,w] of Object.entries(W)){n+=w;if(q<n){const pool=list.filter(x=>x?.rarity===r);return pool.length?pool[Math.floor(Math.random()*pool.length)]:null}}return null}
function chance(base,target,mult){if(!(base>0&&target>base&&mult>1))return 0;const raw=((base*mult-target)/(base*mult-base))*100;const evSafe=(base/target)*90.8;return Math.max(0,Math.min(100,raw,evSafe))}
function simulateCase(list,cost,runs=12000){let total=0,count=0;const rarity={common:0,rare:0,epic:0,mythical:0,legendary:0};for(let i=0;i<runs;i++){const x=pick(list);if(!x)continue;count++;total+=value(x);rarity[x.rarity]=(rarity[x.rarity]||0)+1}return{runs,count,ev:count?total/count:0,rtp:cost?total/(count*cost):0,rarity}}
function simulateUpgrade(list){const vals=[...new Set(list.map(value).filter(v=>v>0))].sort((a,b)=>a-b);let attempts=0,maxRatio=0,maxNet=0,worstChance=100,best=null;for(const base of vals.slice(0,120)){for(const mult of [1.5,2,3,5]){for(const target of vals){if(target<=base||target>base*mult)continue;const p=chance(base,target,mult)/100;const ev=target*p,net=ev-base,ratio=ev/base;attempts++;if(ratio>maxRatio){maxRatio=ratio;maxNet=net;best={base,target,mult,chance:p*100,ev,net,ratio}}worstChance=Math.min(worstChance,p*100)}}}return{attempts,maxRatio,maxNet,worstChance,best,profitable:maxNet>0.000001}}
function run(){if(typeof cases==='undefined'||typeof casePrices==='undefined')return;const report={version:3,at:new Date().toISOString(),cases:{},errors:[]};for(const [key,list] of Object.entries(cases)){const cost=Number(casePrices[key])||0;const s=simulateCase(list,cost);const u=simulateUpgrade(list);report.cases[key]={cost,items:list.length,simulation:s,upgrade:u};if(!cost)report.errors.push(`${key}: missing price`);if(!list.length)report.errors.push(`${key}: empty catalog`);for(const r of Object.keys(W))if(!list.some(x=>x?.rarity===r))report.errors.push(`${key}: missing rarity ${r}`);if(s.rtp<0.82||s.rtp>0.99)report.errors.push(`${key}: RTP ${(s.rtp*100).toFixed(2)}% outside 82-99% QA band`);if(u.profitable)report.errors.push(`${key}: upgrade positive EV detected (${(u.maxRatio*100).toFixed(2)}% of source value)`)}window.__emojiDropsEconomyQA=report;console.info('[Emoji Drops] economy QA',report)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,0),{once:true});else setTimeout(run,0);
})();
