(()=>{'use strict';
const VERSION='final-polish-3';
const $=(s,r=document)=>r.querySelector(s);
function addCSS(){if($('#emoji-drops-final-css'))return;const s=document.createElement('style');s.id='emoji-drops-final-css';s.textContent=`
:root{--ed-live-h:72px;--ed-orange:#ff7b00;--ed-orange2:#ff9a2e}
html{scroll-padding-bottom:var(--ed-live-h)}body{padding-bottom:calc(var(--ed-live-h) + env(safe-area-inset-bottom) + 6px)!important}
body:after{content:'';position:fixed;left:0;right:0;bottom:0;height:env(safe-area-inset-bottom);background:#090909;z-index:44;pointer-events:none}
#cases{scroll-margin-top:92px}.ed-cases-heading{display:flex;align-items:center;justify-content:space-between;margin:4px 0 12px}.ed-cases-heading h2{margin:0;font-size:18px;letter-spacing:.08em;color:#ddd}.ed-cases-heading span{font-size:12px;color:#777}
/* Premium case grid: price is part of the card again. */
.case-card{min-height:245px!important;height:245px!important;cursor:pointer;user-select:none;position:relative;isolation:isolate;overflow:hidden;background:linear-gradient(180deg,#191919 0%,#111 72%,#0d0d0d 100%)!important;border-color:#303030!important;box-shadow:0 8px 28px #0007,inset 0 1px 0 #ffffff08;transition:transform .22s cubic-bezier(.2,.8,.2,1),border-color .22s,box-shadow .22s}.case-card:before{content:'';position:absolute;inset:-35%;z-index:-1;background:radial-gradient(circle at 50% 28%,#ff7b001c,transparent 52%);pointer-events:none;transition:opacity .25s,transform .35s}.case-card:hover{transform:translateY(-5px)!important;border-color:#ff8a16!important;box-shadow:0 0 0 1px #ff7b0030,0 20px 48px #000b}.case-card:hover:before{transform:scale(1.08);opacity:1.35}.case-card:active{transform:translateY(-1px) scale(.992)!important}.case-card:focus-visible{outline:2px solid #ff9a2e;outline-offset:3px}.case-art{position:relative;z-index:1;text-shadow:0 10px 24px #000}.case-info{position:relative;z-index:1}.case-price{display:flex!important;align-items:center;justify-content:center;margin-top:4px!important;padding:4px 0 0!important;background:transparent!important;border:0!important}.case-price span{color:#ff9a2e!important;font-size:21px!important;font-weight:950!important}.case-price small{display:none!important}
/* Multi-open controls. */
#edAmounts{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:7px;margin:8px 0 12px}.amount{min-height:38px;border:1px solid #343434!important;background:#151515!important;border-radius:10px;font-weight:900}.amount:hover{border-color:#ff7b00!important}.amount.active{border-color:#ff7b00!important;background:#2a1709!important;color:#ffb05a}.open-cost{padding:11px 12px;border:1px solid #2d2d2d;border-radius:12px;background:#0d0d0d;margin:8px 0}.case-items{display:grid;grid-template-columns:repeat(auto-fill,minmax(78px,1fr));gap:7px;max-height:190px;overflow:auto;margin:10px 0}.preview-item{border:1px solid var(--rarity,#555);border-radius:12px;background:#151515;padding:7px;text-align:center}.preview-item strong{display:block;font-size:28px}.preview-item span{display:block;color:var(--rarity,#aaa);font-size:9px;font-weight:900}.preview-item small{display:block;color:#aaa;font-size:10px;margin-top:2px}
.modal{opacity:0;transition:opacity .18s ease}.modal.show{opacity:1}.modal .panel{transform:translateY(10px) scale(.985);transition:transform .22s cubic-bezier(.2,.8,.2,1)}.modal.show .panel{transform:none}.ed-final-reel,.case-reel{box-shadow:inset 0 1px 0 #ffffff08,0 10px 30px #0004}.ed-final-item,.reel-item{transition:transform .16s ease,border-color .16s ease}.primary,.reward-top{box-shadow:0 8px 24px #ff7b0022}.primary:hover,.reward-top:not(:disabled):hover{transform:translateY(-1px);box-shadow:0 12px 30px #ff7b0033}
/* Live Drops: no left mask, 1px lower, compact iOS safe-area footprint. */
.live-section{position:fixed!important;left:0!important;right:0!important;bottom:-1px!important;z-index:45!important;margin:0!important;padding:7px 24px calc(6px + env(safe-area-inset-bottom))!important;background:linear-gradient(180deg,#09090900 0%,#090909ef 30%,#090909 100%)!important;border-top:1px solid #292929;box-shadow:0 -10px 30px #0008;backdrop-filter:blur(16px) saturate(120%);overflow:visible}.live-title{display:block!important;width:min(1240px,100%)!important;margin:0 auto 3px!important;padding:0!important;font-size:10px!important;line-height:1!important;letter-spacing:.08em}.live-title span{color:#ff7b00}.live-container{width:min(1240px,100%)!important;margin:0 auto!important;padding:3px 2px 2px!important;gap:8px!important;overflow-x:auto!important;scrollbar-width:none!important;mask-image:none!important}.live-container::-webkit-scrollbar{display:none}.live-drop{flex:0 0 150px!important;height:48px!important;padding:6px 8px!important;border-radius:12px!important;box-shadow:0 5px 18px #0007;transition:transform .18s,filter .18s}.live-drop:hover{transform:translateY(-2px);filter:brightness(1.08)}
/* Online indicator: unmistakable live green dot. */
#onlineCount{display:inline-flex;align-items:center;gap:6px}.online-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#39e75f;box-shadow:0 0 0 3px #39e75f18,0 0 10px #39e75f;animation:onlinePulse 1.8s ease-in-out infinite}@keyframes onlinePulse{0%,100%{opacity:.7;transform:scale(.9)}50%{opacity:1;transform:scale(1.08)}}
/* Mythical is always red in Best Drop / inventory UI. */
.best{border-color:#ef4444!important}.best[style*='--rarity:#ef4444'],.best.mythical{border-color:#ef4444!important}.best span{color:var(--rarity,#ef4444)}
/* Upgrade: fixed circle, percentage sector, rotating inner arrow. */
.ed-final-wheel-circle{--ed-chance:0%;transform:none!important;animation:none!important;background:conic-gradient(from -90deg,#ff7b00 0 var(--ed-chance),#262626 var(--ed-chance) 100%)!important;border:3px solid #ff7b00!important;box-shadow:0 0 30px #ff7b0033!important}.ed-final-wheel-circle:before{transform:translate(-50%,-50%)!important}.ed-final-wheel-circle.ed-stable-spin:before{animation:emojiDropsArrowSpin 5s cubic-bezier(.15,.75,.2,1) both!important}@keyframes emojiDropsArrowSpin{0%{transform:translate(-50%,-50%) rotate(-90deg)!important}72%{transform:translate(-50%,-50%) rotate(1510deg)!important}100%{transform:translate(-50%,-50%) rotate(1440deg)!important}}
@media(max-width:700px){main{padding-left:14px!important;padding-right:14px!important;padding-bottom:calc(var(--ed-live-h) + env(safe-area-inset-bottom) + 6px)!important}.ed-cases-heading{margin-top:0}.case-card{height:220px!important;min-height:220px!important;border-radius:20px!important}.case-art{font-size:64px!important}.live-section{padding-left:10px!important;padding-right:10px!important}.live-container{padding-left:1px!important}.live-drop{flex-basis:148px!important}}@media(max-width:420px){header{height:68px!important}.logo{font-size:20px!important}.top-pill{padding:8px 9px!important}.profile-top{padding:8px 9px!important}.reward-top{padding:8px 9px!important;font-size:12px}.case-card{height:210px!important;min-height:210px!important}.case-art{height:84px!important}.case-price span{font-size:18px!important}#edAmounts{grid-template-columns:repeat(5,minmax(0,1fr))}.live-title{font-size:9px!important}.live-drop{flex-basis:142px!important;height:46px!important}}@media(prefers-reduced-motion:reduce){.modal,.modal .panel,.live-drop,.primary{transition:none!important}.online-dot{animation:none!important}.ed-final-wheel-circle.ed-stable-spin:before{animation:none!important}}
`;document.head.appendChild(s)}
function casesHeading(){const c=$('#cases');if(!c||$('.ed-cases-heading'))return;const h=document.createElement('div');h.className='ed-cases-heading';h.innerHTML='<h2>КЕЙСЫ</h2><span>Выбери коллекцию</span>';c.parentNode.insertBefore(h,c)}
function onlineDot(){const p=$('#onlineCount');if(!p||p.querySelector('.online-dot'))return;const dot=document.createElement('span');dot.className='online-dot';dot.setAttribute('aria-hidden','true');p.prepend(dot)}
function watchDynamicUI(){const root=new MutationObserver(()=>{document.querySelectorAll('.case-price').forEach(x=>x.style.display='flex');onlineDot()});root.observe(document.body,{childList:true,subtree:true});onlineDot()}
function boot(){addCSS();casesHeading();watchDynamicUI();document.documentElement.dataset.finalPolish=VERSION;window.__emojiDropsFinalPolish={version:VERSION,visualContract:true,pricesVisible:true,rewardGuard:false}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
