(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const logoUrl='logo.png';
  const rarity={common:'#9ca3af',rare:'#3b82f6',epic:'#a855f7',mythical:'#ef4444',legendary:'#ff8a00'};
  function css(){if($('#ed-v6-style'))return;const s=document.createElement('style');s.id='ed-v6-style';s.textContent=`
/* Emoji Drops V6: stable visual layer */
:root{--ed-orange:#ff7b00;--ed-orange2:#ff9a2e;--ed-bg:#090909;--ed-card:#121212;--ed-line:#292929}
html,body{background:var(--ed-bg)!important;color:#fff!important}body{overflow-x:hidden!important}
header{height:76px!important;padding:0 34px!important;position:sticky!important;top:0!important;z-index:80!important}
.logo{display:flex!important;align-items:center!important;gap:10px!important;font-size:24px!important;white-space:nowrap!important}.ed-logo-img{width:38px!important;height:38px!important;object-fit:contain!important;border-radius:10px!important;filter:drop-shadow(0 0 9px #ff7b0050)!important}.ed-logo-text{font-weight:900!important}.ed-logo-text span{color:var(--ed-orange)!important}
.top-right{gap:10px!important}.top-pill{padding:10px 14px!important;border-radius:14px!important}.profile-top{padding:10px 14px!important}
.ed-status-dot{display:inline-block!important;width:8px!important;height:8px!important;border-radius:50%!important;margin-right:7px!important;vertical-align:middle!important;animation:edPulse 1.35s infinite!important}.ed-online{background:#20d66b!important;box-shadow:0 0 8px #20d66b!important;color:#20d66b}.ed-live-dot{background:#ff3b30!important;box-shadow:0 0 9px #ff3b30!important;color:#ff3b30}@keyframes edPulse{0%,100%{opacity:.65;transform:scale(.88);box-shadow:0 0 4px currentColor,0 0 0 0 currentColor}50%{opacity:1;transform:scale(1);box-shadow:0 0 12px currentColor,0 0 0 7px transparent}}
main{max-width:1240px!important;padding:30px 24px 70px!important}.hero{margin:0!important;padding:0 0 24px!important;align-items:end!important}.hero h1{font-size:38px!important}.hero p,.hero+.section-title{display:none!important}.hero:after{content:'';display:block;position:absolute;left:0;right:0;bottom:0;height:1px;background:linear-gradient(90deg,transparent,#333 15%,#ff7b0070 50%,#333 85%,transparent)}
#cases{margin-top:28px!important;display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:18px!important}.case-tile{min-width:0!important;display:flex!important;flex-direction:column!important;align-items:stretch!important}.case-tile .case-card{width:100%!important;height:230px!important;min-height:230px!important;position:relative!important;border:1px solid #2c2c2c!important;border-radius:22px!important;padding:20px 16px!important;background:linear-gradient(180deg,#181818,#101010)!important;box-shadow:0 10px 28px #0007!important}.case-tile .case-card:hover{border-color:var(--ed-orange)!important;box-shadow:0 0 0 1px #ff7b0033,0 18px 40px #000!important;transform:translateY(-4px)!important}.case-tile .case-art{height:120px!important;font-size:70px!important}.case-tile .case-name{display:inline-block!important;align-self:center!important;width:max-content!important;max-width:90%!important;padding:7px 14px!important;border:1px solid #3b3b3b!important;border-radius:11px!important;background:#101010!important;font-size:20px!important}.case-tile .case-meta{margin-top:7px!important;color:#777!important}.case-tile .case-price{position:static!important;width:100%!important;border:0!important;background:transparent!important;padding:9px 0 0!important;justify-content:center!important}.case-tile .case-price small{display:none!important}.case-tile .case-price span{font-size:21px!important;color:var(--ed-orange2)!important}
.live-section{margin-top:32px!important}.live-title{font-size:15px!important;margin:0 0 10px!important;display:flex!important;align-items:center!important}.live-title .ed-status-dot{width:8px!important;height:8px!important}.live-container{display:flex!important;flex-direction:row!important;gap:10px!important;overflow:hidden!important;padding:3px 2px 10px!important}.live-drop{flex:0 0 160px!important;height:60px!important;min-width:0!important;border-radius:14px!important}.legendary-live{background:linear-gradient(135deg,#1b1309,#111)!important;box-shadow:0 0 0 1px #ff8a0033,0 0 22px #ff8a0025!important}
#ed-live-fixed{position:fixed;left:18px;bottom:18px;z-index:140;width:42px;height:42px;border:1px solid #ff3b30;border-radius:50%;background:#141414;display:grid;place-items:center;box-shadow:0 0 20px #ff3b3050;pointer-events:none}#ed-live-fixed i{width:11px;height:11px;border-radius:50%;background:#ff3b30;color:#ff3b30;animation:edPulse 1.1s infinite}
.modal{z-index:120!important}.panel{width:min(920px,96vw)!important;max-height:90vh!important;overflow:auto!important;border-radius:24px!important}.panel-body{padding:24px!important}
/* profile */
.profile-layout{grid-template-columns:1fr 1.2fr 1fr!important;gap:14px!important}.profile-center{padding:28px!important;border-color:#ff7b00!important;background:radial-gradient(circle at 50% 0,#ff7b0018,transparent 60%),#0d0d0d!important}.profile-side{gap:9px!important}.profile-btn{min-height:50px!important;border-color:#ff7b00!important}.profile-top-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:9px!important;margin-bottom:14px!important}.profile-top-actions button{min-height:46px!important;border:1px solid #ff7b00!important;border-radius:13px!important;background:#171717!important;font-weight:900!important}.profile-dashboard{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:10px!important;margin:14px 0!important}.profile-stat{border:1px solid #303030!important;border-radius:15px!important;background:#151515!important;padding:13px!important}.profile-stat small{color:#777!important}.profile-stat b{color:#ff9d3d!important;font-size:18px!important}.best-wrap{padding:18px!important;margin-top:14px!important;border:1px solid #2d2d2d!important;border-radius:20px!important;background:#111!important}.inventory{margin-top:20px!important}
/* settings */
.setting:has(#themeToggle){display:none!important}.settings-list{gap:10px!important}.setting{border-radius:14px!important}
/* stats */
.stats{grid-template-columns:repeat(4,1fr)!important;gap:10px!important}.stat{min-width:0!important}.stat b{font-size:24px!important;color:#ff9d3d!important}
/* upgrade */
.upgrade-panel{display:grid!important;grid-template-columns:minmax(0,1fr) 80px minmax(0,1fr)!important;gap:14px!important;align-items:center!important}.upgrade-slot{min-height:180px!important;border:1px solid #303030!important;border-radius:20px!important;background:linear-gradient(180deg,#181818,#101010)!important}.upgrade-arrow{width:62px!important;height:62px!important;border-radius:50%!important;border:1px solid #ff7b00!important;background:#1b120b!important;color:#ff9d3d!important}.upgrade-targets{max-height:220px!important}.upgrade-target.selected{border-color:#ff7b00!important}
/* opening reels */
.case-reels{display:grid!important;gap:11px!important;margin:18px 0 5px!important}.case-reel{height:112px!important;position:relative!important;overflow:hidden!important;border:1px solid #303030!important;border-radius:18px!important;background:linear-gradient(180deg,#171717,#0d0d0d)!important}.case-reel-track{height:100%!important;display:flex!important;align-items:center!important;gap:8px!important;padding:0 9px!important}.reel-item{flex:0 0 88px!important;height:88px!important;border-radius:14px!important;background:#151515!important}.reel-marker{width:3px!important;background:#ff8a00!important;box-shadow:0 0 14px #ff8a00!important}.reel-marker:before{border-top-color:#ff8a00!important}.reel-marker:after{border-bottom-color:#ff8a00!important}
@media(max-width:900px){#cases{grid-template-columns:repeat(2,minmax(0,1fr))!important}.profile-layout{grid-template-columns:1fr!important}.stats{grid-template-columns:1fr 1fr!important}.upgrade-panel{grid-template-columns:1fr!important}.upgrade-arrow{margin:auto!important;transform:rotate(90deg)!important}}
@media(max-width:560px){header{padding:0 14px!important}.top-pill{padding:8px 10px!important}.hero h1{font-size:30px!important}#cases{grid-template-columns:1fr!important}.case-tile .case-card{height:210px!important;min-height:210px!important}.case-tile .case-art{height:105px!important;font-size:64px!important}.live-drop{flex-basis:150px!important}.profile-dashboard{grid-template-columns:1fr!important}.profile-side{grid-template-columns:1fr!important}.stats{grid-template-columns:1fr 1fr!important}}
`;document.head.appendChild(s)}
  function branding(){const l=$('.logo');if(l){l.innerHTML=`<img class="ed-logo-img" src="${logoUrl}" alt="Emoji Drops"><span class="ed-logo-text">Emoji <span>Drops</span></span>`}const online=$('#onlineCount')?.parentElement;if(online&&!online.querySelector('.ed-online')){const n=$('#onlineCount');online.innerHTML='';const d=document.createElement('span');d.className='ed-status-dot ed-online';online.append(d,n);online.append(document.createTextNode(' online'))}const liveTitle=$('.live-title');if(liveTitle&&!liveTitle.querySelector('.ed-live-dot')){liveTitle.innerHTML='<span class="ed-status-dot ed-live-dot"></span><span style="font-size:15px;color:#ddd">LIVE DROPS</span>'}if(!$('#ed-live-fixed')){const x=document.createElement('div');x.id='ed-live-fixed';x.innerHTML='<i></i>';document.body.append(x)}}
  function cleanHero(){const h=$('.hero');if(h)h.querySelector('p')?.remove();document.querySelectorAll('.hero+.section-title').forEach(x=>x.remove())}
  function fixCases(){const g=$('#cases');if(!g)return;$$('.case-tile .case-card',g).forEach(b=>{const open=b.querySelector('.case-price small');if(open)open.remove()});}
  function profile(){const u=window.getUser?.();if(!u)return;const body=$('#profileModal .panel-body');if(!body)return;let actions=$('.profile-top-actions',body);if(!actions){actions=document.createElement('div');actions.className='profile-top-actions';actions.innerHTML='<button id="edProfileMenu">⚙ Меню</button><button id="edProfileExit">↪ Выйти</button>';body.prepend(actions)}$('#edProfileMenu').onclick=window.openSettings;$('#edProfileExit').onclick=window.logout;$('#settingsBtn')?.style.setProperty('display','none');$('#logoutBtn')?.style.setProperty('display','none');const pb=$('#profileBalanceValue');if(pb){pb.textContent='Баланс';pb.onclick=null}let dash=$('.profile-dashboard',body);const s=u.stats||{};if(!dash){dash=document.createElement('div');dash.className='profile-dashboard';$('.best-wrap',body)?.before(dash)}dash.innerHTML=`<div class="profile-stat"><small>Баланс</small><b>${Math.round(u.balance||0)}₽</b></div><div class="profile-stat"><small>Открыто</small><b>${s.opened||0}</b></div><div class="profile-stat"><small>Получено</small><b>${Math.round(s.received||0)}₽</b></div>`}
  function init(){css();branding();cleanHero();fixCases();profile();setInterval(()=>{branding();cleanHero();fixCases();if($('#profileModal')?.classList.contains('show'))profile()},1500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();