(() => {
  'use strict';
  const $=s=>document.querySelector(s);
  const money=v=>Math.round(Number(String(v??0).replace(/[^0-9.,-]/g,'').replace(',','.'))||0);
  const rarityColor=i=>window.rarities?.[i?.rarity]?.color||'#ff7b00';
  function hideSearch(){const el=$('.search-wrap');if(el)el.remove()}
  function syncOpenBalance(){const e=$('#openBalance');if(e)e.textContent=String(money(window.state?.balance))}
  function caseHeader(){const h=$('#openPage .open-header');if(!h)return;let b=$('#openBalance');if(!b){const x=document.createElement('div');x.className='open-balance';x.innerHTML='💰 <span id="openBalance">0</span>₽';h.insertBefore(x,h.querySelector('.back-btn'));}syncOpenBalance()}
  function forceRoulettes(){const c=$('#multiRouletteContainer');if(!c)return;const amount=Math.max(1,Math.min(10,Number(window.state?.openAmount)||1));if(c.children.length===amount&&[...c.children].every(x=>x.classList.contains('multi-roulette')))return;c.innerHTML='';const pool=window.state?.currentCase||[];for(let n=0;n<amount;n++){const lane=document.createElement('div');lane.className='multi-roulette';lane.dataset.lane=n;const pointer=document.createElement('div');pointer.className='new-pointer';const track=document.createElement('div');track.className='multi-track';for(let k=0;k<50;k++){const item=window.getRandomByChance?.(pool)||pool[k%Math.max(pool.length,1)]||{};const el=document.createElement('div');el.className='item';el.textContent=item.emoji||'❔';el.style.borderColor=rarityColor(item);track.appendChild(el)}lane.append(pointer,track);c.appendChild(lane)}}
  function renderCaseItems(){const box=$('#caseItemsList'),items=window.state?.currentCase||[];if(!box||!items.length)return;box.innerHTML='';items.forEach(item=>{const d=document.createElement('div');d.className='case-item-card';d.innerHTML=`<div class="case-item-emoji" style="border-color:${rarityColor(item)}">${item.emoji||'❔'}</div><div class="case-item-rarity" style="color:${rarityColor(item)}">${String(item.rarity||'common').toUpperCase()}</div><div class="case-item-price">${item.price||'0₽'}</div>`;box.appendChild(d)})}
  function ensureLive(){const c=$('#liveContainer');if(!c)return;const pool=Object.values(window.cases||{}).flatMap(x=>Array.isArray(x)?x:[]);if(!pool.length)return;if(c.children.length<8){const names=['Shadow','Blaze','Ghost','Nova','Orion','Razor','Hunter','Pixel','Cyber','Storm'];for(let i=0;i<12;i++){const item=pool[Math.floor(Math.random()*pool.length)],d=document.createElement('div');d.className=`live-drop ${item.rarity||''}`;d.style.borderColor=rarityColor(item);d.innerHTML=`<div class="live-emoji">${item.emoji||'❔'}</div><div class="live-info"><div class="live-user">${names[Math.floor(Math.random()*names.length)]}</div><div class="live-rarity" style="color:${rarityColor(item)}">${String(item.rarity||'common').toUpperCase()}</div></div>`;c.appendChild(d)}}}
  function routeHooks(){if(window.__edLastPolishHooks)return;window.__edLastPolishHooks=true;const originalOpen=window.openCasePage;const originalClose=window.closePage;if(typeof originalOpen==='function')window.openCasePage=function(id){document.body.classList.add('case-route');originalOpen.call(this,id);setTimeout(()=>{caseHeader();syncOpenBalance();forceRoulettes();renderCaseItems()},0)};if(typeof originalClose==='function')window.closePage=function(){originalClose.call(this);document.body.classList.remove('case-route');document.body.classList.remove('ed-opening')}}
  function bind(){hideSearch();routeHooks();caseHeader();syncOpenBalance();if($('#openPage')?.style.display!=='none'){document.body.classList.add('case-route');forceRoulettes();renderCaseItems()}ensureLive();const c=$('#liveContainer');if(c&&!c.dataset.edTimer){c.dataset.edTimer='1';setInterval(()=>{const pool=Object.values(window.cases||{}).flatMap(x=>Array.isArray(x)?x:[]);if(!pool.length)return;const item=pool[Math.floor(Math.random()*pool.length)],d=document.createElement('div');d.className=`live-drop ${item.rarity||''}`;d.style.borderColor=rarityColor(item);d.innerHTML=`<div class="live-emoji">${item.emoji||'❔'}</div><div class="live-info"><div class="live-user">Live Player</div><div class="live-rarity">${String(item.rarity||'common').toUpperCase()}</div></div>`;c.prepend(d);while(c.children.length>24)c.lastElementChild.remove()},1800)}const obs=new MutationObserver(()=>{hideSearch();caseHeader();syncOpenBalance();if(document.body.classList.contains('case-route')){forceRoulettes();renderCaseItems()}});obs.observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,120),{once:true});else setTimeout(bind,120)
})();