(()=>{'use strict';
if(window.__edMasterPolishV5)return;window.__edMasterPolishV5=true;
const css=`
html,body{width:100%!important;min-width:0!important;max-width:none!important;overflow-x:hidden!important}
body{margin:0!important;padding-bottom:118px!important}
main{display:block!important;width:100%!important;max-width:none!important;margin:0!important;padding:12px clamp(8px,1.6vw,28px) 136px!important;box-sizing:border-box!important}
.hero,.hero-content,.hero h1,.hero p{display:none!important}
.home-divider{display:block!important;width:100%!important;height:2px!important;margin:0 0 14px!important;border:0!important;border-radius:999px!important;background:linear-gradient(90deg,transparent,#ff7b00 7%,#ff9a2e 50%,#ff7b00 93%,transparent)!important;box-shadow:0 0 12px #ff7b0038!important}
#cases,.cases{display:grid!important;width:100%!important;max-width:none!important;margin:0!important;padding:0!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:clamp(8px,1.15vw,18px)!important}
#cases .case-tile,.cases .case-tile{width:100%!important;min-width:0!important;max-width:none!important;margin:0!important;padding:0!important}
#cases .case-card,.cases .case-card{display:flex!important;width:100%!important;min-width:0!important;max-width:none!important;height:clamp(205px,15vw,285px)!important;min-height:0!important;margin:0!important;padding:clamp(10px,1vw,17px)!important;box-sizing:border-box!important;flex-direction:column!important;align-items:center!important;justify-content:flex-start!important;overflow:hidden!important;contain:layout paint style!important;transform:translateZ(0)!important;backface-visibility:hidden!important;-webkit-backface-visibility:hidden!important;transition:transform .18s cubic-bezier(.22,1,.36,1),border-color .18s ease,box-shadow .18s ease!important}
#cases .case-card:hover,.cases .case-card:hover{transform:translate3d(0,-4px,0)!important}
#cases .case-art,.cases .case-art{display:grid!important;place-items:center!important;width:100%!important;height:clamp(64px,6vw,92px)!important;min-height:64px!important;flex:0 0 clamp(64px,6vw,92px)!important;font-size:clamp(48px,4.4vw,72px)!important}
#cases .case-info,.cases .case-info{display:flex!important;width:100%!important;min-width:0!important;min-height:0!important;flex:1!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important}
#cases .case-name,.cases .case-name{max-width:100%!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;font-size:clamp(13px,1.1vw,18px)!important}
#cases .case-meta,.cases .case-meta{font-size:clamp(9px,.85vw,13px)!important}
#cases .case-price span,.cases .case-price span{font-size:clamp(15px,1.2vw,20px)!important}
.live-section{position:fixed!important;left:0!important;right:0!important;bottom:0!important;width:100vw!important;max-width:none!important;margin:0!important;padding:7px clamp(8px,1.5vw,28px) calc(7px + env(safe-area-inset-bottom))!important;box-sizing:border-box!important;z-index:2147483000!important}
.live-title,.live-container{width:100%!important;max-width:none!important;margin-left:0!important;margin-right:0!important;box-sizing:border-box!important}.live-container{display:flex!important;gap:9px!important;overflow-x:auto!important;scrollbar-width:none!important}.live-container::-webkit-scrollbar{display:none}.live-container>*{flex:0 0 auto!important}
.case-card,.primary,.secondary,.profile-btn,.upgrade-item,.upgrade-target,.amount,.live-drop{backface-visibility:hidden!important;-webkit-backface-visibility:hidden!important;transition:transform .16s ease,opacity .16s ease,border-color .16s ease,box-shadow .16s ease!important}
.case-card:active,.primary:active,.secondary:active,.profile-btn:active,.upgrade-item:active,.upgrade-target:active{transform:scale(.985)!important}
.ed-insufficient{opacity:.42!important;filter:grayscale(.85)!important;cursor:not-allowed!important;pointer-events:none!important}
.final-upgrade{width:100%!important;max-width:none!important}
.ed-wheel-shell{position:relative;width:min(360px,78vw);aspect-ratio:1;margin:0 auto 12px;display:grid;place-items:center}.ed-wheel{position:relative;width:84%;height:84%;border-radius:50%;background:conic-gradient(from -90deg,#ff8a00 0 20%,#ffb347 20% 27%,#2b2e36 27% 100%);border:7px solid #12141a;box-shadow:0 0 0 2px #ff8a0060,0 12px 40px #0008,inset 0 0 28px #000;transform:translateZ(0);contain:layout paint}.ed-wheel:before{content:'';position:absolute;inset:12px;border-radius:50%;border:1px solid #ffffff24}.ed-wheel:after{content:'';position:absolute;inset:28px;border-radius:50%;border:1px dashed #ffffff18}.ed-wheel-label{position:absolute;z-index:3;left:50%;top:50%;transform:translate(-50%,-50%);width:24%;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;background:#101217;border:2px solid #ff9a2e;color:#ffbd6b;font-size:clamp(14px,2vw,19px);font-weight:1000;box-shadow:0 0 22px #ff7b0040,inset 0 0 18px #000}.ed-wheel-mark{position:absolute;z-index:3;left:50%;top:7%;transform:translateX(-50%);font-size:9px;font-weight:1000;color:#fff;letter-spacing:.1em}.ed-pointer{position:absolute;z-index:8;left:50%;top:50%;width:0;height:0;transform:translate(-50%,-50%) rotate(0deg);transform-origin:50% 50%;will-change:transform}.ed-pointer:before{content:'';position:absolute;left:-3px;top:-43%;width:6px;height:43%;border-radius:99px;background:linear-gradient(#fff,#ff9a2e);box-shadow:0 0 12px #ff7b00}.ed-pointer:after{content:'';position:absolute;left:-15px;top:-51%;border-left:15px solid transparent;border-right:15px solid transparent;border-top:29px solid #fff;filter:drop-shadow(0 0 8px #ff7b00)}.ed-pointer-center{position:absolute;left:-11px;top:-11px;width:22px;height:22px;border-radius:50%;background:#ff9a2e;border:3px solid #111;box-shadow:0 0 15px #ff7b00}.ed-chance{display:flex;flex-wrap:wrap;justify-content:center;gap:6px;margin:2px 0 10px}.ed-chance span{padding:5px 8px;border-radius:8px;background:#17191f;border:1px solid #333;font-size:10px;font-weight:900}
@media(max-width:1100px){#cases,.cases{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
@media(max-width:600px){main{padding:8px 6px 124px!important}#cases,.cases{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important}.case-tile .case-card{height:clamp(174px,46vw,212px)!important;padding:8px!important;border-radius:15px!important}.case-tile .case-art{height:clamp(52px,15vw,70px)!important;min-height:52px!important;flex-basis:clamp(52px,15vw,70px)!important;font-size:clamp(38px,11vw,54px)!important}.case-tile .case-name{font-size:clamp(12px,3.5vw,16px)!important}.case-tile .case-meta{font-size:8px!important}.case-tile .case-price span{font-size:14px!important}.live-section{padding-left:6px!important;padding-right:6px!important}.ed-wheel-shell{width:min(300px,82vw)}}
@media(max-width:380px){#cases,.cases{gap:6px!important}.case-tile .case-card{height:168px!important}.ed-wheel-shell{width:min(260px,82vw)}}
@media(pointer:coarse){.case-card:hover,.profile-btn:hover{transform:none!important}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
const s=document.createElement('style');s.id='emoji-drops-master-polish';s.textContent=css;document.head.appendChild(s);
})();