(() => {
  'use strict';
  const root=document.getElementById('mobileRoot');
  const all=[]; if(window.cases)Object.values(window.cases).forEach(items=>items.forEach(item=>all.push(item)));
  const q=new URLSearchParams(location.search), view=q.get('view')||'home', caseId=q.get('case');
  const rarityColor=r=>window.rarities?.[r]?.color||'#ff7a18';
  const caseNames=Object.keys(window.cases||{});
  const caseEmoji={smile:'😀',moves:'🕺',nature:'🌿',food:'🍔',animals:'🐶',transport:'🚗',sport:'⚽',games:'🎮',money:'💰',full:'🔥'};
  const price=id=>Number(window.casePrices?.[id]??100);
  function shell(title,body){root.innerHTML=`<section class="m-view"><div class="m-view-head"><a href="mobile.html">←</a><div><div class="m-kicker">EMOJI DROPS</div><h1>${title}</h1></div></div>${body}</section>`;}
  function renderHome(){root.innerHTML=`<section class="m-hero"><div class="m-kicker">EMOJI DROPS</div><h1>Открывай.<br><span>Лови редкие дропы.</span></h1><p>Быстрые кейсы, яркие награды и плавные открытия — специально под iPhone.</p><a class="m-primary" href="mobile.html?view=cases">Открыть кейсы <span>→</span></a></section><section class="m-section"><div class="m-section-head"><h2>Популярные кейсы</h2><a href="mobile.html?view=cases">Все</a></div><div class="m-cases">${caseNames.slice(0,6).map(id=>`<a class="m-case" href="mobile.html?case=${encodeURIComponent(id)}"><span>${caseEmoji[id]||'📦'}</span><strong>${id[0].toUpperCase()+id.slice(1)}</strong><em>${price(id)}₽</em></a>`).join('')}</div></section><section class="m-live"><div class="m-section-head"><h2>Live Drops</h2><span>● LIVE</span></div><div id="mLive" class="m-live-list"></div></section>`;startLive();}
  function renderCases(){shell('Кейсы',`<div class="m-cases m-cases-all">${caseNames.map(id=>`<a class="m-case" href="mobile.html?case=${encodeURIComponent(id)}"><span>${caseEmoji[id]||'📦'}</span><strong>${id[0].toUpperCase()+id.slice(1)}</strong><em>${price(id)}₽</em></a>`).join('')}</div>`);}
  function pick(items){let total=0;items.forEach(x=>total+=Number(x.chance||1));let n=Math.random()*total;for(const x of items){n-=Number(x.chance||1);if(n<=0)return x;}return items[items.length-1];}
  function renderCase(id){const items=window.cases?.[id]||[];if(!items.length){shell('Кейс не найден','<div class="m-empty">Кейс не найден</div>');return;}shell(id[0].toUpperCase()+id.slice(1),`<div class="m-case-open"><div class="m-roulette" id="mRoulette"><div class="m-pointer">▼</div><div class="m-roll-track" id="mTrack">${Array.from({length:14},()=>{const x=pick(items);return `<span style="border-color:${rarityColor(x.rarity)}">${x.emoji}</span>`}).join('')}</div></div><div class="m-case-meta"><span>${items.length} предметов</span><strong>${price(id)}₽</strong></div><button class="m-primary m-open" id="mOpen">Открыть кейс <span>→</span></button><div class="m-reward" id="mReward"></div></div>`);document.getElementById('mOpen')?.addEventListener('click',()=>openMobileCase(items));}
  function openMobileCase(items){const track=document.getElementById('mTrack'),reward=document.getElementById('mReward'),btn=document.getElementById('mOpen');if(!track||!reward||!btn)return;btn.disabled=true;const win=pick(items),seq=Array.from({length:30},()=>pick(items));seq[24]=win;track.innerHTML=seq.map(x=>`<span style="border-color:${rarityColor(x.rarity)}">${x.emoji}</span>`).join('');const offset=24*72-((track.parentElement.clientWidth-72)/2);track.style.transform=`translate3d(-${offset}px,0,0)`;track.classList.add('rolling');setTimeout(()=>{track.classList.remove('rolling');reward.innerHTML=`<div class="m-reward-card" style="--rarity:${rarityColor(win.rarity)}"><div class="m-reward-rarity">${win.rarity.toUpperCase()}</div><div class="m-reward-emoji">${win.emoji}</div><strong>${win.name||'Награда'}</strong><b>${win.price}₽</b></div>`;btn.disabled=false;},1850);}
  function renderProfile(){shell('Профиль',`<div class="m-profile-card"><div class="m-avatar">👤</div><h2 id="mProfileName">Гость</h2><div class="m-profile-balance">Баланс <b id="mProfileBalance">1000₽</b></div></div><div class="m-profile-actions"><a href="mobile.html?view=login">🔐 Войти / регистрация</a><a href="/profile/statistics">📊 Статистика</a><a href="/upgrade">⬆️ Upgrade</a></div>`);loadLocalProfile();}
  function renderLogin(){shell('Вход',`<div class="m-auth"><input id="mEmail" type="email" autocomplete="username" placeholder="Почта"><input id="mPassword" type="password" autocomplete="current-password" placeholder="Пароль"><button class="m-primary" id="mLogin">Войти <span>→</span></button><p id="mAuthHint">Для входа с ПК и iPhone настрой Supabase в js/cloud-config.js.</p></div>`);loadMobileAuth();}
  function renderUpgrade(){shell('Upgrade',`<div class="m-upgrade"><div class="m-upgrade-icon">⬆️</div><h2>Upgrade</h2><p>Выбери предмет и попробуй улучшить его.</p><a class="m-primary" href="/upgrade">Открыть полный Upgrade <span>→</span></a></div>`);}
  function startLive(){const live=document.getElementById('mLive');if(!live||!all.length)return;const add=()=>{const item=all[Math.floor(Math.random()*all.length)],el=document.createElement('div');el.className='m-drop';el.innerHTML=`<div class="emoji">${item.emoji}</div><div class="rarity" style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()}</div>`;live.prepend(el);while(live.children.length>7)live.lastElementChild.remove();};for(let i=0;i<7;i++)add();setInterval(add,1800);}
  function loadLocalProfile(){try{const users=JSON.parse(localStorage.getItem('users')||'[]'),email=localStorage.getItem('currentUser'),u=users.find(x=>x.email===email);if(u){document.getElementById('mProfileName').textContent=u.nickname||'Player';document.getElementById('mProfileBalance').textContent=Number(u.balance||1000).toLocaleString('ru-RU')+'₽';}}catch{}}
  function loadMobileAuth(){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>{const cfg=window.EMOJI_DROPS_SUPABASE||{};if(!cfg.url||!cfg.publishableKey)return;const client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});document.getElementById('mLogin')?.addEventListener('click',async()=>{const email=document.getElementById('mEmail').value.trim(),password=document.getElementById('mPassword').value;const {error}=await client.auth.signInWithPassword({email,password});if(error)return alert(error.message);location.href='mobile.html?view=profile';});};document.head.appendChild(s);}
  const cfgScript=document.createElement('script');cfgScript.src='js/cloud-config.js?v=20260825m2';cfgScript.onload=()=>{if(caseId)renderCase(caseId);else if(view==='cases')renderCases();else if(view==='profile')renderProfile();else if(view==='login')renderLogin();else if(view==='upgrade')renderUpgrade();else renderHome();};document.head.appendChild(cfgScript);
})();
