(()=>{'use strict';
/* Emoji Drops — shared motion + UI polish. Visual-only. */
const STYLE='ed-motion-system';
const reduced=()=>window.__emojiDropsPerf?.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;
function inject(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
.case-card,.top-pill,.profile-top,.profile-btn,.primary,.secondary,.amount,.close,.reward-btn,.inventory-item,.preview-item,.best,.stat{transition:transform .22s cubic-bezier(.2,.8,.2,1),opacity .22s ease,border-color .22s ease,box-shadow .22s ease,background-color .22s ease!important}.case-card:active,.primary:not(:disabled):active,.secondary:not(:disabled):active,.profile-btn:not(:disabled):active,.amount:not(:disabled):active,.close:not(:disabled):active{transform:scale(.975)!important}.case-card:hover{transform:translateY(-6px) scale(1.008)}.primary:not(:disabled):hover,.reward-btn:not(:disabled):hover{transform:translateY(-2px);box-shadow:0 10px 28px rgba(255,123,0,.18)}.secondary:not(:disabled):hover,.profile-btn:not(:disabled):hover,.close:not(:disabled):hover{transform:translateY(-2px)}.case-card:focus-visible,.primary:focus-visible,.secondary:focus-visible,.profile-btn:focus-visible,.amount:focus-visible,.close:focus-visible{outline:2px solid #ff9a2e;outline-offset:3px}
.modal.show{animation:edModalIn .2s ease both}.modal.show .panel{animation:edPanelIn .28s cubic-bezier(.2,.85,.2,1) both}@keyframes edModalIn{from{opacity:0}to{opacity:1}}@keyframes edPanelIn{from{opacity:0;transform:translateY(14px) scale(.985)}to{opacity:1;transform:none}}
.live-drop{animation:edLiveIn .45s cubic-bezier(.2,.85,.2,1) both}.live-drop:nth-child(2){animation-delay:.025s}.live-drop:nth-child(3){animation-delay:.05s}@keyframes edLiveIn{from{opacity:0;transform:translateX(-22px) scale(.96)}to{opacity:1;transform:none}}
.ed-final-item{transition:transform .18s ease,filter .18s ease,box-shadow .18s ease!important}.ed-final-item:hover{transform:translateY(-2px);filter:brightness(1.08)}.ed-final-win{animation:edWinIn .35s cubic-bezier(.2,.85,.2,1) both}@keyframes edWinIn{from{opacity:0;transform:translateY(9px) scale(.97)}to{opacity:1;transform:none}}
/* Upgrade wheel: the circle stays fixed; only the arrow inside it moves. */
.ed-final-wheel{position:relative;isolation:isolate}.ed-final-wheel:before{content:'';position:absolute;width:178px;height:178px;border-radius:50%;border:1px solid rgba(255,123,0,.22);box-shadow:0 0 28px rgba(255,123,0,.12);pointer-events:none;z-index:0}.ed-final-wheel:after{content:'';display:none!important}.ed-final-wheel-circle{--ed-chance:50%;--ed-arrow-angle:-65deg;position:relative;z-index:1;width:154px!important;height:154px!important;border:4px solid #ff7b00!important;border-radius:50%!important;display:grid!important;place-items:center!important;background:radial-gradient(circle,#0c0c0c 0 46%,transparent 47%),conic-gradient(from -90deg,#ff7b00 0 var(--ed-chance),#242424 var(--ed-chance) 100%)!important;box-shadow:0 0 20px rgba(255,123,0,.18),inset 0 0 24px rgba(0,0,0,.8)!important;filter:none!important;overflow:hidden!important;transform:none!important;animation:none!important}.ed-final-wheel-circle:after{content:'➤';position:absolute;left:50%;top:50%;z-index:4;font-size:22px;line-height:1;color:#fff7ed;text-shadow:0 0 10px rgba(255,123,0,.85);pointer-events:none;transform:translate(-50%,-50%) rotate(var(--ed-arrow-angle)) translateX(43px);transform-origin:center center;transition:transform .22s cubic-bezier(.2,.8,.2,1)}.ed-final-wheel-circle.ed-upgrade-spin:after{animation:edUpgradeArrowSpin 5s cubic-bezier(.12,.72,.16,1) both!important}@keyframes edUpgradeArrowSpin{0%{transform:translate(-50%,-50%) rotate(var(--ed-arrow-angle)) translateX(43px)}100%{transform:translate(-50%,-50%) rotate(calc(var(--ed-arrow-angle) + 1440deg)) translateX(43px)}}.ed-final-wheel-circle.ed-upgrade-win{box-shadow:0 0 32px rgba(68,255,145,.35),inset 0 0 25px rgba(68,255,145,.12)!important;border-color:#4dff91!important}.ed-final-wheel-circle.ed-upgrade-lose{box-shadow:0 0 32px rgba(255,65,65,.28),inset 0 0 25px rgba(255,65,65,.1)!important;border-color:#ff4d4d!important}.ed-final-wheel-circle.ed-upgrade-spin{animation:none!important}.ed-final-wheel-circle.ed-upgrade-spin{color:transparent!important}
.ed-upgrade-outcome{display:none;margin-top:10px;padding:9px 14px;border-radius:12px;text-align:center;font-size:14px;font-weight:1000}.ed-upgrade-outcome.show{display:block}.ed-upgrade-outcome.win{color:#4dff91;border:1px solid rgba(77,255,145,.35);background:rgba(77,255,145,.08)}.ed-upgrade-outcome.lose{color:#ff5b5b;border:1px solid rgba(255,77,77,.35);background:rgba(255,77,77,.08)}
.ed-final-chance{padding:8px 13px;border-radius:999px;background:#0e0e0e;border:1px solid rgba(255,123,0,.15);font-size:14px!important;font-weight:1000!important}.ed-final-item-btn.selected{box-shadow:0 0 0 1px #ff7b00,0 8px 18px rgba(255,123,0,.13)!important}.ed-final-mults button.active{box-shadow:0 0 0 1px rgba(255,123,0,.3),0 6px 16px rgba(255,123,0,.12)}#edDoUpgrade{min-height:44px;font-weight:1000}
@media(max-width:900px){.ed-final-wheel-circle{width:138px!important;height:138px!important}.ed-final-wheel:before{width:160px;height:160px}.ed-final-wheel-circle:after{font-size:20px;transform:translate(-50%,-50%) rotate(var(--ed-arrow-angle)) translateX(37px)}.ed-final-wheel-circle.ed-upgrade-spin:after{animation-name:edUpgradeArrowSpinMobile!important}}
@keyframes edUpgradeArrowSpinMobile{0%{transform:translate(-50%,-50%) rotate(var(--ed-arrow-angle)) translateX(37px)}100%{transform:translate(-50%,-50%) rotate(calc(var(--ed-arrow-angle) + 1440deg)) translateX(37px)}}
@media(prefers-reduced-motion:reduce){.ed-final-wheel-circle.ed-upgrade-spin:after{animation:none!important}}
`;
document.head.appendChild(s)}
function patchOnline(){const n=document.getElementById('onlineCount');if(!n)return;const host=n.parentElement;if(!host||host.dataset.edOnlinePatched==='1')return;host.innerHTML=`<span class="online-dot" aria-hidden="true"></span><span id="onlineCount">${n.textContent||'128'}</span> online`;host.dataset.edOnlinePatched='1'}
function patch(){inject();patchOnline()}
function observe(){patch();const mo=new MutationObserver(()=>patch());mo.observe(document.body,{childList:true,subtree:true});window.addEventListener('pagehide',()=>mo.disconnect(),{once:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe,{once:true});else observe();
window.__emojiDropsMotion={version:8,reduced:reduced(),visualOnly:true};
})();
