(()=>{'use strict';
const REWARD=100;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const users=()=>{try{return JSON.parse(localStorage.getItem('users')||'[]')}catch{return[]}};
const current=()=>{const e=localStorage.getItem('currentUser');return users().find(u=>u.email===e)||null};
const save=u=>{const a=users(),i=a.findIndex(x=>x.email===u.email);if(i>=0){a[i]=u;localStorage.setItem('users',JSON.stringify(a))}};
const value=i=>Number(i?.value)||Number(i?.price)||Number(String(i?.value||i?.price||0).replace(/[^0-9.]/g,''))||0;
const rank=r=>({common:1,rare:2,epic:3,mythical:4,legendary:5}[r]||0);
function style(){if($('#ed-polish-v7'))return;const s=document.createElement('style');s.id='ed-polish-v7';s.textContent=`
.logo{display:flex!important;align-items:center!important;gap:10px!important;white-space:nowrap}.ed-logo{margin:0!important;flex:0 0 38px!important;width:38px!important;height:38px!important;object-fit:contain!important;border-radius:10px!important}.logo span{display:inline-block!important}
.top-pill.ed-online{display:flex!important;align-items:center!important;gap:8px!important}.ed-dot{width:8px!important;height:8px!important;display:inline-block!important;flex:0 0 8px!important;border-radius:50%!important;background:#ff3b30!important;box-shadow:0 0 9px #ff3b30!important;animation:edPulse 1.15s ease-in-out infinite!important}@keyframes edPulse{0%,100%{opacity:.5;transform:scale(.86)}50%{opacity:1;transform:scale(1);box-shadow:0 0 15px #ff3b30}}
.amounts{justify-content:center!important;margin:10px 0 8px!important}.amount{width:42px!important;height:42px!important;transition:.18s!important}.amount.active{border-color:var(--orange)!important;background:linear-gradient(145deg,#38200d,#211309)!important;box-shadow:0 0 0 2px #ff7b0033,0 0 16px #ff7b0022!important;color:#fff!important;transform:translateY(-1px)}#amountLabel{display:none!important}#costRow{text-align:center!important;margin:4px 0 12px!important;font-size:15px!important;color:#aaa}.open-cost{font-size:20px!important}.reel-actions{justify-content:center!important;align-items:center!important}.reel-actions button{min-width:150px!important;height:48px!important}.reel-actions #openBtn{min-width:180px!important}
.profile-layout{grid-template-columns:1fr 1.4fr 1fr!important;grid-template-areas:'center center center' 'left center2 right'!important;align-items:start!important}.profile-center{grid-area:center!important;margin-bottom:4px!important}.profile-layout>.profile-side:first-child{grid-area:left!important}.profile-layout>.profile-side:last-child{grid-area:right!important}.profile-side{justify-content:flex-start!important;padding-top:0!important}.profile-btn{min-height:50px!important}.profile-dashboard{margin-top:8px!important;position:relative!important;z-index:2!important}.best-wrap{margin-top:28px!important}.best-wrap .section-title{margin-bottom:10px!important}.best{width:min(620px,100%)!important;justify-content:center!important;min-height:86px!important;padding:16px 22px!important;border-radius:22px!important;background:radial-gradient(circle at 50% 0,#ff7b0018,transparent 65%),linear-gradient(145deg,#181818,#101010)!important;box-shadow:0 12px 35px #0008,inset 0 1px 0 #fff1!important}.best strong{font-size:50px!important}.inventory{margin-top:30px!important;padding:22px 18px 20px!important;border:1px solid #2d2d2d!important;border-radius:24px!important;background:linear-gradient(180deg,#141414,#0d0d0d)!important;box-shadow:inset 0 1px 0 #fff1,0 15px 45px #0006!important}.inventory .section-title{text-align:center!important;font-size:20px!important;margin:0 0 18px!important;position:relative!important}.inventory .section-title:after{content:'';display:block;width:74px;height:2px;margin:8px auto 0;background:linear-gradient(90deg,transparent,#ff7b00,transparent);box-shadow:0 0 12px #ff7b00}.inventory-item{transition:transform .2s,box-shadow .2s!important}.inventory-item:hover{transform:translateY(-3px)!important;box-shadow:0 12px 28px #0008!important}
.case-tile .case-card{height:285px!important}.case-tile .case-art{min-height:145px!important}.case-info{min-height:92px!important}.case-card{transition:transform .22s,border-color .22s,box-shadow .22s!important}
.upgrade-runtime{display:grid!important;grid-template-columns:minmax(0,1fr) 190px minmax(0,1fr)!important;gap:16px!important;align-items:stretch!important}.upgrade-wheel-col{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:12px!important}.upgrade-wheel{width:158px!important;height:158px!important;border-radius:50%!important;padding:7px!important;background:conic-gradient(#ff7b00,#ff9d3d,#7c3aed,#ef4444,#ff7b00)!important;box-shadow:0 0 34px #ff7b0040!important}.upgrade-wheel>div{width:100%!important;height:100%!important;border-radius:50%!important;display:grid!important;place-items:center!important;background:radial-gradient(circle,#2b190b 0 45%,#111 46% 70%,#1b1008 71%)!important;border:2px solid #ffb35c!important;font-size:36px!important;color:#ffb35c!important}.upgrade-wheel.spinning{animation:edWheel .9s cubic-bezier(.15,.8,.1,1)!important}@keyframes edWheel{to{transform:rotate(1080deg)}}
.ed-reward-ready{box-shadow:0 0 0 1px #ff7b0066,0 0 20px #ff7b0022!important}.ed-reward-disabled{filter:saturate(.3)!important;opacity:.65!important}
@media(max-width:900px){.case-tile .case-card{height:250px!important}.case-tile .case-art{min-height:115px!important}.profile-layout{grid-template-columns:1fr!important;grid-template-areas:'center' 'left' 'right'!important}.profile-side{padding-top:0!important}.profile-dashboard{margin-top:6px!important}.upgrade-runtime{grid-template-columns:1fr!important}.upgrade-wheel-col{order:2!important}.upgrade-box.target{order:3!important}.upgrade-box.source{order:1!important}.upgrade-submit{order:4!important}}
@media(max-width:520px){header{padding:0 12px!important}.logo{font-size:20px!important;gap:7px!important}.ed-logo{width:32px!important;height:32px!important;flex-basis:32px!important}.top-right{gap:6px!important}.profile-top{padding:9px 10px!important}.cases{grid-template-columns:1fr!important;gap:14px!important}.case-tile .case-card{height:225px!important;border-radius:20px!important}.case-tile .case-art{min-height:100px!important;font-size:68px!important}.panel-body{padding:18px!important}.amount{width:40px!important;height:40px!important}.reel-actions{width:100%!important}.reel-actions button{flex:1!important;min-width:0!important}.upgrade-wheel{width:136px!important;height:136px!important}.best{min-height:78px!important}.inventory{padding:18px 12px!important}}
`;document.head.appendChild(s)}
function branding(){const l=$('.logo');if(l)l.innerHTML='<img class="ed-logo" src="logo.png" alt="Emoji Drops" decoding="async"><span>Emoji <b style="color:#ff7b00">Drops</b></span>';const o=$('#onlineCount')?.closest('.top-pill');if(o){o.classList.add('ed-online');o.querySelectorAll('.ed-dot').forEach(x=>x.remove());o.insertAdjacentHTML('afterbegin','<span class="ed-dot"></span>')}const t=$('.live-title');if(t)t.innerHTML='<span class="ed-dot"></span> LIVE DROPS';const b=$('#balance')?.parentElement;if(b)b.querySelectorAll('.ed-balance-icon').forEach(x=>x.remove())}
function canBuyAny(u){return [...$$('#cases .case-card')].map(c=>Number((c.querySelector('.case-price span')?.textContent||'').replace(/[^0-9]/g,''))).filter(Boolean).some(p=>Number(u?.balance||0)>=p)}
function claim(e){e?.preventDefault();e?.stopImmediatePropagation();const u=current();if(!u)return window.openAuth?.();if(canBuyAny(u))return;u.balance=Number(u.balance||0)+REWARD;u.stats||={opened:0,upgrades:0,spent:0,received:0};u.stats.received+=REWARD;save(u);window.renderAll?.();syncRewards()}
function bindRewards(){['rewardHeader','rewardProfile'].forEach(id=>{const old=$('#'+id);if(!old||old.dataset.v7)return;const b=old.cloneNode(true);old.replaceWith(b);b.dataset.v7='1';b.addEventListener('click',claim,true)})}
function syncRewards(){const u=current(),ok=!!u&&!canBuyAny(u);['rewardHeader','rewardProfile'].forEach(id=>{const b=$('#'+id);if(!b)return;b.textContent=`Получить ${REWARD}₽`;b.disabled=!ok;b.classList.toggle('ed-reward-ready',ok);b.classList.toggle('ed-reward-disabled',!ok)});$('#ed-reward-hint')?.remove()}
function persistBest(){const u=current();if(!u||!Array.isArray(u.inventory))return;const best=u.inventory.slice().sort((a,b)=>(rank(b.rarity)-rank(a.rarity))||(value(b)-value(a)))[0]||null;if(JSON.stringify(u.bestDrop)!==JSON.stringify(best))save({...u,bestDrop:best})}
function tick(){branding();bindRewards();syncRewards();persistBest()}
function init(){style();tick();setInterval(tick,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();