(()=>{'use strict';
const REWARD=100;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const users=()=>{try{return JSON.parse(localStorage.getItem('users')||'[]')}catch{return[]}};
const current=()=>{const e=localStorage.getItem('currentUser');return users().find(u=>u.email===e)||null};
const save=u=>{const a=users(),i=a.findIndex(x=>x.email===u.email);if(i>=0){a[i]=u;localStorage.setItem('users',JSON.stringify(a))}};
const value=i=>Number(i?.value)||Number(i?.price)||Number(String(i?.value||i?.price||0).replace(/[^0-9.]/g,''))||0;
const rank=r=>({common:1,rare:2,epic:3,mythical:4,legendary:5}[r]||0);
function style(){if($('#ed-polish-v7'))return;const s=document.createElement('style');s.id='ed-polish-v7';s.textContent=`
.logo{display:flex!important;align-items:center!important;gap:10px!important;white-space:nowrap}.ed-logo{margin:0!important;flex:0 0 38px!important;width:38px!important;height:38px!important;object-fit:contain!important;border-radius:10px!important}.logo span{display:inline-block!important}
.top-pill.ed-online{display:flex!important;align-items:center!important;gap:8px!important}.ed-dot{width:8px!important;height:8px!important;display:inline-block!important;flex:0 0 8px!important;border-radius:50%!important;background:#ff3b30!important;box-shadow:0 0 9px #ff3b30!important;animation:edPulse 1.15s ease-in-out infinite!important}@keyframes edPulse{0%,100%{opacity:.5;transform:scale(.86)}50%{opacity:1;transform:scale(1);box-shadow:0 0 15px #ff3b30}}
.amounts{justify-content:center!important;margin:10px 0 8px!important}.amount{width:42px!important;height:42px!important;transition:.18s!important}.amount.active{border-color:var(--orange)!important;background:linear-gradient(145deg,#38200d,#211309)!important;box-shadow:0 0 0 2px #ff7b0033,0 0 16px #ff7b0022!important;color:#fff!important;transform:translateY(-1px)}#amountLabel{display:none!important}#costRow{text-align:center!important;margin:4px 0 12px!important;font-size:15px!important;color:#aaa}.open-cost{font-size:20px!important}.reel-actions{justify-content:center!important;align-items:center!important}.reel-actions button{min-width:150px!important;height:48px!important}.reel-actions #openBtn{min-width:180px!important}
.profile-layout{grid-template-columns:1fr 1.4fr 1fr!important;grid-template-areas:'center center center' 'left center2 right'!important;align-items:start!important}.profile-center{grid-area:center!important;margin-bottom:4px!important}.profile-layout>.profile-side:first-child{grid-area:left!important}.profile-layout>.profile-side:last-child{grid-area:right!important}.profile-side{justify-content:flex-start!important;padding-top:0!important}.profile-btn{min-height:50px!important}.profile-dashboard{margin-top:8px!important;position:relative!important;z-index:2!important}.best-wrap{margin-top:28px!important}.best-wrap .section-title{margin-bottom:10px!important}.best{width:min(620px,100%)!important;justify-content:center!important;min-height:86px!important;padding:16px 22px!important;border-radius:22px!important;background:radial-gradient(circle at 50% 0,#ff7b0018,transparent 65%),linear-gradient(145deg,#181818,#101010)!important;box-shadow:0 12px 35px #0008,inset 0 1px 0 #fff1!important}.best strong{font-size:50px!important}.inventory{margin-top:30px!important;padding:22px 18px 20px!important;border:1px solid #2d2d2d!important;border-radius:24px!important;background:linear-gradient(180deg,#141414,#0d0d0d)!important;box-shadow:inset 0 1px 0 #fff1,0 15px 45px #0006!important}.inventory .section-title{text-align:center!important;font-size:20px!important;margin:0 0 18px!important;position:relative!important}.inventory .section-title:after{content:'';display:block;width:74px;height:2px;margin:8px auto 0;background:linear-gradient(90deg,transparent,#ff7b00,transparent);box-shadow:0 0 12px #ff7b00}.inventory-item{transition:transform .2s,box-shadow .2s!important}.inventory-item:hover{transform:translateY(-3px)!important;box-shadow:0 12px 28px #0008!important}
.case-tile .case-card{height:285px!important}.case-tile .case-art{min-height:145px!important}.case-info{min-height:92px!important}.case-card{transition:transform .22s,border-color .22s,box-shadow .22s!important}
.upgrade-runtime{display:grid!important;grid-template-columns:minmax(0,1fr) 190px minmax(0,1fr)!important;gap:16px!important;align-items:stretch!important}.upgrade-wheel-col{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:12px!important}.upgrade-wheel{width:158px!important;height:158px!important;border-radius:50%!important;padding:7px!important;background:conic-gradient(#ff7b00,#ff9d3d,#7c3aed,#ef4444,#ff7b00)!important;box-shadow:0 0 34px #ff7b0040!important}.upgrade-wheel>div{width:100%!important;height:100%!important;border-radius:50%!important;display:grid!important;place-items:center!important;background:radial-gradient(circle,#2b190b 0 45%,#111 46% 70%,#1b1008 71%)!important;border:2px solid #ffb35c!important;font-size:36px!important;color:#ffb35c!important}.upgrade-wheel.spinning{animation:edWheel .9s cubic-bezier(.15,.8,.1,1)!important}@keyframes edWheel{to{transform:rotate(1080deg)}}
/* Real upgrade wheel and pointer */
.upgrade-arrow{position:relative!important;width:156px!important;height:156px!important;border-radius:50%!important;padding:8px!important;border:0!important;background:conic-gradient(from -18deg,#ff7b00 0 18deg,#17110c 18deg 42deg,#ff9d3d 42deg 60deg,#17110c 60deg 84deg,#7c3aed 84deg 104deg,#17110c 104deg 132deg,#ef4444 132deg 150deg,#17110c 150deg 180deg,#ff7b00 180deg 198deg,#17110c 198deg 222deg,#ff9d3d 222deg 240deg,#17110c 240deg 264deg,#7c3aed 264deg 284deg,#17110c 284deg 312deg,#ef4444 312deg 330deg,#17110c 330deg 360deg)!important;box-shadow:0 0 35px #ff7b0033,0 0 0 1px #ff7b0066!important;display:grid!important;place-items:center!important;color:#ffb35c!important;font-size:0!important;transition:filter .2s,box-shadow .2s!important}.upgrade-arrow:before{content:'➤';position:absolute;z-index:5;left:50%;top:-18px;transform:translateX(-50%) rotate(90deg);width:34px;height:34px;display:grid;place-items:center;font-size:25px;color:#ff9d3d;text-shadow:0 0 12px #ff7b00;filter:drop-shadow(0 3px 4px #000);pointer-events:none}.upgrade-arrow:after{content:'';width:100%;height:100%;border-radius:50%;background:radial-gradient(circle at 50% 45%,#2b190b 0 26%,#111 27% 48%,#20140b 49% 58%,#0d0d0d 59% 100%);border:2px solid #ffb35c;box-shadow:inset 0 0 25px #ff7b0022;grid-area:1/1;pointer-events:none}.upgrade-arrow.spinning{animation:edUpgradeSpin 1.65s cubic-bezier(.12,.78,.08,1);filter:brightness(1.12);box-shadow:0 0 55px #ff7b0055,0 0 0 2px #ff9d3d88!important}@keyframes edUpgradeSpin{0%{transform:rotate(0)}15%{transform:rotate(110deg)}55%{transform:rotate(760deg)}82%{transform:rotate(1030deg)}100%{transform:rotate(1080deg)}}
.upgrade-panel{align-items:center!important}.upgrade-arrow{justify-self:center}.upgrade-slot{transition:transform .2s,box-shadow .2s,border-color .2s}.upgrade-slot:hover{transform:translateY(-2px);box-shadow:0 12px 30px #0008}.upgrade-item,.upgrade-target,.upgrade-mult,.primary,.secondary,.profile-btn,.amount,.reel-fast,.close{transition:transform .18s,border-color .18s,background .18s,box-shadow .18s,filter .18s}.upgrade-item:hover,.upgrade-target:hover,.amount:hover{transform:translateY(-2px)}.primary:hover,.profile-btn.reward:hover{transform:translateY(-1px);filter:brightness(1.06);box-shadow:0 10px 25px #ff7b0022}.secondary:hover,.reel-fast:hover,.close:hover{transform:translateY(-1px)}
.modal{transition:opacity .18s ease}.modal:not(.show){pointer-events:none}.panel{animation:edPanelIn .22s cubic-bezier(.2,.8,.2,1)}@keyframes edPanelIn{from{opacity:0;transform:translateY(10px) scale(.985)}to{opacity:1;transform:none}}
.case-card,.inventory-item,.best,.profile-center,.stat,.upgrade-slot{backface-visibility:hidden;contain:layout paint}.case-card:active,.primary:active,.secondary:active,.profile-btn:active{transform:scale(.985)}
.ed-reward-ready{box-shadow:0 0 0 1px #ff7b0066,0 0 20px #ff7b0022!important}.ed-reward-disabled{filter:saturate(.3)!important;opacity:.65!important}
@media(max-width:900px){.case-tile .case-card{height:250px!important}.case-tile .case-art{min-height:115px!important}.profile-layout{grid-template-columns:1fr!important;grid-template-areas:'center' 'left' 'right'!important}.profile-side{padding-top:0!important}.profile-dashboard{margin-top:6px!important}.upgrade-runtime{grid-template-columns:1fr!important}.upgrade-wheel-col{order:2!important}.upgrade-box.target{order:3!important}.upgrade-box.source{order:1!important}.upgrade-submit{order:4!important}.upgrade-arrow{width:142px!important;height:142px!important}}
@media(max-width:520px){header{padding:0 12px!important}.logo{font-size:20px!important;gap:7px!important}.ed-logo{width:32px!important;height:32px!important;flex-basis:32px!important}.top-right{gap:6px!important}.profile-top{padding:9px 10px!important}.cases{grid-template-columns:1fr!important;gap:14px!important}.case-tile .case-card{height:225px!important;border-radius:20px!important}.case-tile .case-art{min-height:100px!important;font-size:68px!important}.panel-body{padding:18px!important}.amount{width:40px!important;height:40px!important}.reel-actions{width:100%!important}.reel-actions button{flex:1!important;min-width:0!important}.upgrade-arrow{width:128px!important;height:128px!important}.upgrade-arrow:before{top:-15px;width:30px;height:30px;font-size:22px}.best{min-height:78px!important}.inventory{padding:18px 12px!important}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.01ms!important}}
`;document.head.appendChild(s)}
function branding(){const l=$('.logo');if(l)l.innerHTML='<img class="ed-logo" src="logo.png" alt="Emoji Drops" decoding="async"><span>Emoji <b style="color:#ff7b00">Drops</b></span>';const o=$('#onlineCount')?.closest('.top-pill');if(o){o.classList.add('ed-online');o.querySelectorAll('.ed-dot').forEach(x=>x.remove());o.insertAdjacentHTML('afterbegin','<span class="ed-dot"></span>')}const t=$('.live-title');if(t)t.innerHTML='<span class="ed-dot"></span> LIVE DROPS';const b=$('#balance')?.parentElement;if(b)b.querySelectorAll('.ed-balance-icon').forEach(x=>x.remove())}
function canBuyAny(u){return [...$$('#cases .case-card')].map(c=>Number((c.querySelector('.case-price span')?.textContent||'').replace(/[^0-9]/g,''))).filter(Boolean).some(p=>Number(u?.balance||0)>=p)}
function claim(e){e?.preventDefault();e?.stopImmediatePropagation();const u=current();if(!u)return window.openAuth?.();if(canBuyAny(u))return;u.balance=Number(u.balance||0)+REWARD;u.stats||={opened:0,upgrades:0,spent:0,received:0};u.stats.received+=REWARD;save(u);window.renderAll?.();syncRewards()}
function bindRewards(){['rewardHeader','rewardProfile'].forEach(id=>{const old=$('#'+id);if(!old||old.dataset.v7)return;const b=old.cloneNode(true);old.replaceWith(b);b.dataset.v7='1';b.addEventListener('click',claim,true)})}
function syncRewards(){const u=current(),ok=!!u&&!canBuyAny(u);['rewardHeader','rewardProfile'].forEach(id=>{const b=$('#'+id);if(!b)return;b.textContent=`Получить ${REWARD}₽`;b.disabled=!ok;b.classList.toggle('ed-reward-ready',ok);b.classList.toggle('ed-reward-disabled',!ok)});$('#ed-reward-hint')?.remove()}
function persistBest(){const u=current();if(!u||!Array.isArray(u.inventory))return;const best=u.inventory.slice().sort((a,b)=>(rank(b.rarity)-rank(a.rarity))||(value(b)-value(a)))[0]||null;if(JSON.stringify(u.bestDrop)!==JSON.stringify(best))save({...u,bestDrop:best})}
function hookUpgrade(){const btn=$('#upgradeDo');if(btn&&!btn.dataset.wheelHook){btn.dataset.wheelHook='1';btn.addEventListener('click',()=>{const wheel=$('.upgrade-arrow');if(!wheel)return;wheel.classList.remove('spinning');void wheel.offsetWidth;wheel.classList.add('spinning');window.setTimeout(()=>wheel.classList.remove('spinning'),1750)},true)}}
function loadUpgrade(){if($('#ed-upgrade-script'))return;const s=document.createElement('script');s.id='ed-upgrade-script';s.src='js/upgrade-polish.js?v=1';s.async=false;document.head.appendChild(s)}
function tick(){branding();bindRewards();syncRewards();persistBest();hookUpgrade();loadUpgrade()}
function init(){style();tick();setInterval(tick,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();