(()=>{'use strict';
const DAY=86400000, REWARD=100, KEY='emojiDrops.reward.v6', MAX=3;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const users=()=>{try{return JSON.parse(localStorage.getItem('users')||'[]')}catch{return[]}};
const current=()=>{const e=localStorage.getItem('currentUser');return users().find(u=>u.email===e)||null};
const save=u=>{const a=users(),i=a.findIndex(x=>x.email===u.email);if(i>=0){a[i]=u;localStorage.setItem('users',JSON.stringify(a))}};
const state=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const setState=s=>localStorage.setItem(KEY,JSON.stringify(s));
const money=n=>`${Math.round(Number(n)||0)}₽`;
function style(){if($('#ed-polish-v3'))return;const s=document.createElement('style');s.id='ed-polish-v3';s.textContent=`
.logo{display:flex!important;align-items:center!important;gap:10px!important;white-space:nowrap}.ed-logo{margin:0!important;flex:0 0 38px!important}.logo span{display:inline-block!important}
.top-pill.ed-online{display:flex!important;align-items:center!important;gap:8px!important}.ed-dot{width:8px!important;height:8px!important;flex:0 0 8px!important}
.ed-balance-icon{width:24px;height:24px;display:inline-grid;place-items:center;margin-right:7px;border:1px solid #ff9a2e;border-radius:8px;background:linear-gradient(145deg,#2a190d,#17110b);color:#ffb35c;font-size:13px;font-weight:1000;box-shadow:inset 0 0 10px #ff7b0022,0 0 10px #ff7b0012}
.amounts{justify-content:center!important;margin:10px 0 8px!important}.amount{width:42px!important;height:42px!important}.amount.active{border-color:var(--orange)!important;background:linear-gradient(145deg,#38200d,#211309)!important;box-shadow:0 0 0 2px #ff7b0033,0 0 16px #ff7b0022!important;color:#fff!important;transform:translateY(-1px)}#amountLabel{display:none!important}#costRow{text-align:center!important;margin:4px 0 12px!important;font-size:15px!important;color:#aaa}.open-cost{font-size:20px!important}.reel-actions{justify-content:center!important;align-items:center!important}.reel-actions button{min-width:150px!important;height:48px!important}.reel-actions #openBtn{min-width:180px!important}
.profile-layout{grid-template-columns:1fr 1.4fr 1fr!important;grid-template-areas:'center center center' 'left center2 right'!important;align-items:start!important}.profile-center{grid-area:center!important;margin-bottom:4px!important}.profile-layout>.profile-side:first-child{grid-area:left!important}.profile-layout>.profile-side:last-child{grid-area:right!important}.profile-side{justify-content:flex-start!important;padding-top:0!important}.profile-btn{min-height:50px!important}.profile-dashboard{margin-top:8px!important;position:relative!important;z-index:2!important}.best-wrap{margin-top:28px!important}.best-wrap .section-title{margin-bottom:10px!important}.best{width:min(620px,100%)!important;justify-content:center!important;min-height:86px!important;padding:16px 22px!important;border-radius:22px!important;background:radial-gradient(circle at 50% 0,#ff7b0018,transparent 65%),linear-gradient(145deg,#181818,#101010)!important;box-shadow:0 12px 35px #0008,inset 0 1px 0 #fff1!important}.best strong{font-size:50px!important}.inventory{margin-top:30px!important;padding:22px 18px 20px!important;border:1px solid #2d2d2d!important;border-radius:24px!important;background:linear-gradient(180deg,#141414,#0d0d0d)!important;box-shadow:inset 0 1px 0 #fff1,0 15px 45px #0006!important}.inventory .section-title{text-align:center!important;font-size:20px!important;margin:0 0 18px!important;position:relative!important}.inventory .section-title:after{content:'';display:block;width:74px;height:2px;margin:8px auto 0;background:linear-gradient(90deg,transparent,#ff7b00,transparent);box-shadow:0 0 12px #ff7b00}.inventory-grid{position:relative!important}.inventory-grid:empty:after{content:'Инвентарь пуст';display:block;text-align:center;color:#666;padding:20px}.inventory-item{transition:transform .2s,box-shadow .2s!important}.inventory-item:hover{transform:translateY(-3px)!important;box-shadow:0 12px 28px #0008!important}
.reward-btn,.profile-btn.reward{transition:.2s!important}.reward-btn:disabled,.profile-btn.reward:disabled{filter:saturate(.35)!important}.ed-reward-hint{font-size:11px;color:#888;margin-top:6px;text-align:center}.ed-reward-hint.ready{color:#ff9d3d}
@media(max-width:900px){.profile-layout{grid-template-columns:1fr!important;grid-template-areas:'center' 'left' 'right'!important}.profile-side{padding-top:0!important}.profile-dashboard{margin-top:6px!important}}
`;document.head.appendChild(s)}
function branding(){const l=$('.logo');if(l&&!l.querySelector('.ed-logo'))l.innerHTML='<img class="ed-logo" src="logo.png" alt="Emoji Drops" decoding="async"><span>Emoji <b style="color:#ff7b00">Drops</b></span>';const o=$('#onlineCount')?.closest('.top-pill');if(o){o.classList.add('ed-online');o.innerHTML='<span class="ed-dot"></span><span id="onlineCount">'+($('#onlineCount')?.textContent||'128')+'</span> online'}const b=$('#balance')?.parentElement;if(b&&!b.querySelector('.ed-balance-icon'))b.insertAdjacentHTML('afterbegin','<span class="ed-balance-icon">₽</span>');const label=$('#amountLabel');if(label)label.classList.add('hidden')}
function stats(u){u.stats||={opened:0,upgrades:0,spent:0,received:0};return u.stats}
function canBuyAny(u){const cards=[...$$('#cases .case-card')];const prices=cards.map(c=>{const x=c.querySelector('.case-price span')?.textContent||'';return Number(x.replace(/[^0-9]/g,''))||0}).filter(Boolean);return prices.length?prices.some(p=>Number(u?.balance||0)>=p):false}
function rewardInfo(){let s=state();if(!s.nextAt)s={claims:0,nextAt:0};if(s.nextAt&&Date.now()>=s.nextAt)s={claims:0,nextAt:0};return s}
function rewardText(){const s=rewardInfo();if(s.nextAt)return `Доступно через ${fmt(s.nextAt-Date.now())}`;if(s.claims>=MAX)return `Доступно через ${fmt(DAY)}`;return `Получить ${REWARD}₽`}
function fmt(ms){let x=Math.max(0,Math.ceil(ms/1000)),h=Math.floor(x/3600),m=Math.floor(x%3600/60),q=x%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(q).padStart(2,'0')}`}
function updateRewards(){const u=current(),s=rewardInfo(),allowed=!!u&&!canBuyAny(u)&&s.claims<MAX&&!s.nextAt;[$('#rewardHeader'),$('#rewardProfile')].forEach(b=>{if(!b)return;b.textContent=allowed?`Получить ${REWARD}₽`:rewardText();b.disabled=!allowed});let hint=$('#ed-reward-hint');if(!hint){hint=document.createElement('div');hint.id='ed-reward-hint';hint.className='ed-reward-hint';const p=$('#rewardProfile')?.parentElement;if(p)p.appendChild(hint)}hint.textContent=allowed?'Награда доступна, когда ни один кейс недоступен по балансу.':(s.nextAt?`Следующая награда через ${fmt(s.nextAt-Date.now())}`:(s.claims>=MAX?'Лимит 3 награды достигнут.':'Пополни баланс открытием кейса.'));hint.classList.toggle('ready',allowed)}
function claim(e){e?.preventDefault();e?.stopImmediatePropagation();const u=current();if(!u)return window.openAuth?.();const s=rewardInfo();if(canBuyAny(u)||s.nextAt||s.claims>=MAX)return updateRewards();stats(u);u.balance=Number(u.balance||0)+REWARD;u.stats.received+=REWARD;save(u);const claims=(s.claims||0)+1;setState(claims>=MAX?{claims,nextAt:Date.now()+DAY}:{claims,nextAt:0});$('#balance').textContent=Math.round(u.balance);updateRewards();if(typeof window.profileSync==='function')window.profileSync()}
function bindRewards(){['rewardHeader','rewardProfile'].forEach(id=>{const b=$('#'+id);if(!b||b.dataset.v3)return;const n=b.cloneNode(true);b.replaceWith(n);n.dataset.v3='1';n.addEventListener('click',claim,true)});updateRewards()}
function tick(){updateRewards();window.setTimeout(tick,1000)}
function init(){style();branding();bindRewards();tick();setInterval(()=>{branding();bindRewards()},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();
