(()=>{'use strict';
/* Production repair layer: no external services, no blocking startup. */
const CASE_ID='smile-box';
const CASE_PRICE=35;
const CASE_NAME='Смайл-бокс';
const CASE_ICON='😎';
const ITEMS=['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😇','🙂','🙃','😉','😌','😍','🥰','😘','😗','😙','😚','😋','😛','😝','😜','🤪','🤨','🧐','🤓','😎','🥳','🤩','🤗','🤭','🤔','🫡'];
const RARITIES=['common','common','common','common','common','common','common','common','common','common','common','common','common','common','rare','rare','rare','rare','rare','rare','rare','rare','rare','epic','epic','epic','epic','epic','epic','mythical','mythical','mythical','mythical','legendary'];
const MULT={common:.28,rare:.62,epic:1.18,mythical:2.35,legendary:4.8};
function money(n){return `${Math.round(Number(n)||0)}₽`}
function installCase(){if(typeof cases==='undefined'||typeof casePrices==='undefined')return false;if(!Array.isArray(cases[CASE_ID]))cases[CASE_ID]=[];cases[CASE_ID]=Array.from({length:35},(_,i)=>({emoji:ITEMS[i],rarity:RARITIES[i],value:Math.max(1,Math.round(CASE_PRICE*(MULT[RARITIES[i]]||.28)*(.92+i*.16/34))),price:money(Math.max(1,Math.round(CASE_PRICE*(MULT[RARITIES[i]]||.28)*(.92+i*.16/34)))),caseId:CASE_ID}));casePrices[CASE_ID]=CASE_PRICE;return true}
function addCard(){const grid=document.querySelector('#cases');if(!grid||grid.querySelector(`[data-case="${CASE_ID}"]`))return;if(!installCase())return;const a=document.createElement('article');a.className='case-tile';a.innerHTML=`<button class="case-card" type="button" data-case="${CASE_ID}" aria-label="Открыть кейс ${CASE_NAME}"><div class="case-art">${CASE_ICON}</div><div class="case-info"><div class="case-name">${CASE_NAME}</div><div class="case-meta">35 предметов</div><div class="case-price"><span>${money(CASE_PRICE)}</span></div></div></button>`;grid.appendChild(a);a.querySelector('button').addEventListener('click',()=>{if(typeof buildOpenModal==='function')buildOpenModal(CASE_ID);else document.dispatchEvent(new CustomEvent('emoji-drops-open-case',{detail:CASE_ID}))})}
function layout(){const s=document.createElement('style');s.textContent=`#cases{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:18px!important}.case-tile .case-card{height:245px!important;min-height:245px!important}.case-tile .case-art{height:105px!important;flex:0 0 105px!important;font-size:76px!important}@media(max-width:900px){#cases{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:520px){#cases{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.case-tile .case-card{height:210px!important;min-height:210px!important;padding:12px!important}.case-tile .case-art{height:72px!important;flex-basis:72px!important;font-size:56px!important}.case-tile .case-name{font-size:18px!important}}@media(max-width:380px){#cases{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.case-tile .case-card{height:190px!important;min-height:190px!important}.case-tile .case-art{height:60px!important;flex-basis:60px!important;font-size:48px!important}.case-tile .case-name{font-size:15px!important}}.case-card{backface-visibility:hidden;-webkit-backface-visibility:hidden;contain:layout paint}.case-reel-track,.upgrade-wheel{transform:translateZ(0);backface-visibility:hidden}.live-section{position:fixed!important;left:0!important;right:0!important;bottom:0!important;z-index:900!important}`;document.head.appendChild(s)}
function boot(){installCase();layout();addCard();requestAnimationFrame(addCard)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();