(()=>{'use strict';
/* Emoji Drops — final product-quality pass. UI only; transaction engine remains authoritative. */
const Q={version:1,sort:'value-desc',motion:true};
const safeUsers=()=>{try{const x=JSON.parse(localStorage.getItem('users')||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const safeEmail=()=>localStorage.getItem('currentUser');
const safeUser=()=>{const e=safeEmail();return e?safeUsers().find(x=>x?.email===e)||null:null};
const safeSave=u=>{if(!u)return;const a=safeUsers(),i=a.findIndex(x=>x?.email===u.email);if(i>=0)a[i]=u;else a.push(u);localStorage.setItem('users',JSON.stringify(a))};
/* Compatibility bridge for the inline settings UI. Never throws if storage is damaged. */
if(typeof window.getUser!=='function')window.getUser=safeUser;
if(typeof window.saveUser!=='function')window.saveUser=safeSave;
const rarity={common:['COMMON','#9ca3af',55],rare:['RARE','#3b82f6',27],epic:['EPIC','#a855f7',12],mythical:['MYTHICAL','#ef4444',5],legendary:['LEGENDARY','#ff8a00',1]};
const val=x=>Number(x?.value)||Number(x?.price)||Number(String(x?.value||x?.price||0).replace(/[^0-9.\-]/g,''))||0;
function css(){if(document.getElementById('ed-quality-css'))return;const s=document.createElement('style');s.id='ed-quality-css';s.textContent=`
html{scroll-behavior:smooth}button{-webkit-tap-highlight-color:transparent}button:focus-visible,input:focus-visible{outline:2px solid #ff8a00;outline-offset:2px}.case-card,.profile-btn,.primary,.secondary,.amount,.ed-final-item-btn,.upgrade-mult,.upgrade-target{transition:transform .16s ease,opacity .16s ease,border-color .16s ease,box-shadow .16s ease}.case-card:active,.profile-btn:active,.primary:active,.secondary:active,.amount:active,.ed-final-item-btn:active,.upgrade-mult:active{transform:scale(.98)}
.ed-quality-odds{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:12px}.ed-quality-odds div{border:1px solid #292929;background:#111;border-radius:10px;padding:7px 4px;text-align:center}.ed-quality-odds b{display:block;font-size:11px}.ed-quality-odds span{font-size:10px;color:#999}.ed-wheel-shell{position:relative;width:145px;height:145px;border-radius:50%;display:grid;place-items:center}.ed-wheel-circle-bg{position:absolute;inset:0;border-radius:50%;background:#111;border:3px solid #ff7b00;box-shadow:0 0 28px #ff7b0033}.ed-wheel-sector{position:absolute;inset:8px;border-radius:50%;background:conic-gradient(from -90deg,#ff7b00 var(--chance-angle),#21170f var(--chance-angle) 100%);opacity:.9;mask:radial-gradient(circle,transparent 0 47%,#000 48%)}.ed-wheel-arrow{position:absolute;left:50%;top:50%;width:54px;height:4px;transform-origin:0 50%;transform:rotate(var(--arrow-angle,0deg));background:#fff;border-radius:999px;box-shadow:0 0 10px #fff;transition:transform 900ms cubic-bezier(.2,.85,.15,1)}.ed-wheel-arrow:after{content:'';position:absolute;right:-1px;top:50%;transform:translate(0,-50%);border-top:7px solid transparent;border-bottom:7px solid transparent;border-left:13px solid #fff}.ed-wheel-center{position:absolute;z-index:2;width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#111;border:2px solid #ff7b00;font-size:13px;font-weight:900}.ed-wheel-status{position:absolute;bottom:-22px;font-size:10px;color:#999;font-weight:900;white-space:nowrap}.ed-quality-inventory-tools{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.ed-quality-inventory-tools button{border:1px solid #333;background:#151515;border-radius:10px;padding:8px 10px;font-size:12px;font-weight:800}.ed-quality-inventory-tools button.active{border-color:#ff7b00;color:#ff9d3d}.ed-quality-note{font-size:10px;color:#777;margin-top:7px}.modal.show .panel{animation:edPanelIn .18s ease both}@keyframes edPanelIn{from{opacity:0;transform:translateY(8px) scale(.985)}to{opacity:1;transform:none}}@media(max-width:700px){.ed-quality-odds{grid-template-columns:repeat(5,minmax(48px,1fr));overflow:auto}.ed-quality-odds div{min-width:52px}.ed-wheel-shell{width:138px;height:138px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.case-card,.profile-btn,.primary,.secondary,.amount,.ed-final-item-btn,.upgrade-mult,.upgrade-target,.ed-wheel-arrow{transition:none!important}.modal.show .panel{animation:none}}
`;document.head.appendChild(s)}
function addOdds(){const modal=document.getElementById('edOpenModal'),preview=modal?.querySelector('#edCaseItems');if(!modal||!preview||modal.querySelector('.ed-quality-odds'))return;const row=document.createElement('div');row.className='ed-quality-odds';Object.entries(rarity).forEach(([k,[label,color,ch]])=>{const d=document.createElement('div');d.style.borderColor=color;d.innerHTML=`<b style="color:${color}">${label}</b><span>${ch}%</span>`;row.appendChild(d)});preview.insertAdjacentElement('beforebegin',row);const n=document.createElement('div');n.className='ed-quality-note';n.textContent='Шансы относятся к редкости; конкретный предмет внутри редкости выбирается случайно.';row.insertAdjacentElement('afterend',n)}
function wheel(){const c=document.querySelector('.ed-final-wheel-circle');if(!c)return;let chance=0;const txt=document.getElementById('edChance')?.textContent||'';const m=txt.match(/(\d+(?:\.\d+)?)%/);if(m)chance=Math.max(0,Math.min(100,Number(m[1])));if(!c.querySelector('.ed-wheel-shell')){c.innerHTML='<div class="ed-wheel-shell"><div class="ed-wheel-circle-bg"></div><div class="ed-wheel-sector"></div><div class="ed-wheel-arrow"></div><div class="ed-wheel-center">⚡</div><div class="ed-wheel-status">CHANCE</div></div>';c.style.background='transparent';c.style.border='0';c.style.boxShadow='none';c.style.fontSize='0'}const shell=c.querySelector('.ed-wheel-shell'),sector=c.querySelector('.ed-wheel-sector'),arrow=c.querySelector('.ed-wheel-arrow'),center=c.querySelector('.ed-wheel-center');if(!shell||!sector||!arrow)return;const angle=chance*3.6;sector.style.setProperty('--chance-angle',`${angle}deg`);const centerAngle=-90+angle/2;arrow.style.setProperty('--arrow-angle',`${centerAngle}deg`);if(center)center.textContent=c.textContent.includes('✓')?'✓':c.textContent.includes('×')?'×':'⚡';const playing=(txt.includes('Прокрутка')||txt.includes('WIN')||txt.includes('LOSE'));if(playing){arrow.classList.add('spinning');arrow.style.transform=`rotate(${centerAngle+720+Math.min(270,angle)}deg)`;setTimeout(()=>{arrow.style.transform=`rotate(${centerAngle+(txt.includes('LOSE')?360:0)}deg)`},950)}}
function inventoryTools(){const box=document.getElementById('edInventory');if(!box||box.dataset.qualityTools)return;box.dataset.qualityTools='1';const wrap=document.createElement('div');wrap.className='ed-quality-inventory-tools';[['value-desc','💎 Дорогие'],['value-asc','⬆ Дешёвые'],['rarity-desc','⭐ Редкость']].forEach(([mode,label],i)=>{const b=document.createElement('button');b.type='button';b.textContent=label;if(i===0)b.classList.add('active');b.onclick=()=>{wrap.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');sortInventory(mode)};wrap.appendChild(b)});box.parentElement?.insertBefore(wrap,box);sortInventory('value-desc')}
function sortInventory(mode){const box=document.getElementById('edInventory');if(!box)return;const rank={common:1,rare:2,epic:3,mythical:4,legendary:5};const items=[...box.children];items.sort((a,b)=>{const av=Number((a.querySelector('small')?.textContent||'').replace(/[^0-9.-]/g,''))||0,bv=Number((b.querySelector('small')?.textContent||'').replace(/[^0-9.-]/g,''))||0;if(mode==='value-asc')return av-bv;if(mode==='rarity-desc')return (rank[b.querySelector('span')?.textContent?.toLowerCase()]||0)-(rank[a.querySelector('span')?.textContent?.toLowerCase()]||0);return bv-av});box.replaceChildren(...items)}
function bind(){css();addOdds();wheel();const inv=document.getElementById('edInventory');if(inv)inventoryTools();const observer=new MutationObserver(()=>{addOdds();wheel();const b=document.getElementById('edInventory');if(b&&!b.dataset.qualityTools)inventoryTools()});observer.observe(document.body,{childList:true,subtree:true});document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const open=[...document.querySelectorAll('.modal.show')].reverse()[0];if(!open)return;const close=open.querySelector('.close:not(:disabled)');if(close)close.click()});window.__emojiDropsProductQuality=Q}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
