(() => {
  'use strict';
  const normalize=(path=location.pathname)=>(path.replace(/\/+/g,'/').replace(/\/$/,'')||'/');
  const route=()=>{const p=normalize();const m=p.match(/^\/case\/([a-z0-9_-]+)$/i);if(m)return{name:'case',id:m[1].toLowerCase()};if(p==='/cases')return{name:'cases'};if(p==='/profile')return{name:'profile'};if(p==='/profile/statistics')return{name:'statistics'};if(p==='/profile/history')return{name:'history'};if(p==='/profile/settings')return{name:'settings'};if(p==='/upgrade')return{name:'upgrade'};return{name:'home'}};
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const visible=(el,on,display='')=>{if(!el)return;el.style.display=on?display:'none';el.setAttribute('aria-hidden',on?'false':'true')};
  const call=(name,...args)=>typeof window[name]==='function'?window[name](...args):undefined;
  const navigate=(path,replace=false)=>{const target=path.startsWith('/')?path:`/${path}`;if(normalize()!==normalize(target)){(replace?history.replaceState:history.pushState).call(history,{},'',target)}window.scrollTo({top:0,behavior:'instant'});render()};
  let nativeCase=null;
  function closeAll(){['profilePage','settingsOverlay','statsOverlay','historyOverlay','routeRoot'].forEach(id=>visible(document.getElementById(id),false));const up=document.getElementById('edUpgrade2');if(up)up.classList.remove('open','closing');const page=document.getElementById('openPage');if(page)visible(page,false);document.body.classList.remove('case-route')}
  function homeChrome(on=true){visible(q('body > header'),on);visible(q('body > .top-line'),on);visible(q('body > .search-wrap'),on);visible(q('body > .live-drops-bar'),on)}
  function showCase(id){const main=q('body > main'),grid=q('main > .cases'),page=document.getElementById('openPage');visible(main,true);visible(grid,false);homeChrome(false);document.body.classList.add('case-route');window.__edRouteRenderingCase=true;try{(nativeCase||window.openCasePage)?.(id)}finally{window.__edRouteRenderingCase=false}visible(page,true,'flex')}
  function render(){const r=route();closeAll();homeChrome(true);if(r.name==='home'||r.name==='cases'){visible(q('body > main'),true);visible(q('main > .cases'),true);qa('.case').forEach(c=>c.style.display='flex');return}if(r.name==='case'){showCase(r.id);return}homeChrome(false);visible(q('body > main'),false);if(!window.state?.currentUser){navigate('/');setTimeout(()=>call('openAuth','login'),0);return}if(r.name==='profile'){call('openProfile');visible(document.getElementById('profilePage'),true,'flex');return}if(r.name==='statistics'){call('openStats');visible(document.getElementById('statsOverlay'),true,'flex');return}if(r.name==='history'){call('openHistory');visible(document.getElementById('historyOverlay'),true,'flex');return}if(r.name==='settings'){call('openSettings');visible(document.getElementById('settingsOverlay'),true,'flex');return}if(r.name==='upgrade'){call('openUpgradeMenu');return}}
  function bridge(){if(nativeCase||typeof window.openCasePage!=='function')return;nativeCase=window.openCasePage;window.__edNativeCaseOpen=nativeCase;window.openCasePage=function(id){if(window.__edRouteRenderingCase)return nativeCase.call(this,id);navigate(`/case/${encodeURIComponent(id)}`)};const oldClose=window.closePage;if(typeof oldClose==='function')window.closePage=function(){if(route().name==='case'){navigate('/');return}return oldClose.apply(this,arguments)}}
  document.addEventListener('click',e=>{const link=e.target.closest('[data-route]');if(link){e.preventDefault();e.stopImmediatePropagation();navigate(link.dataset.route);return}const back=e.target.closest('[data-back]');if(back){e.preventDefault();e.stopImmediatePropagation();navigate('/');return}const profile=e.target.closest('#profileBtn');if(profile&&window.state?.currentUser){e.preventDefault();e.stopImmediatePropagation();navigate('/profile');return}},true);
  window.addEventListener('popstate',render);window.EmojiDropsRouter={navigate,render,route};window.openProfileRoute=()=>navigate('/profile');window.openUpgradeRoute=()=>navigate('/upgrade');window.openStatsRoute=()=>navigate('/profile/statistics');window.openHistoryRoute=()=>navigate('/profile/history');window.openSettingsRoute=()=>navigate('/profile/settings');
  const init=()=>{bridge();setTimeout(()=>{bridge();render()},0)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();