(() => {
  'use strict';
  const normalize=(path=location.pathname)=>(path.replace(/\/+/g,'/').replace(/\/$/,'')||'/');
  const route=()=>{const p=normalize();const m=p.match(/^\/case\/([a-z0-9_-]+)$/i);if(m)return{name:'case',id:m[1].toLowerCase()};if(p==='/cases')return{name:'cases'};if(p==='/profile')return{name:'profile'};if(p==='/profile/statistics')return{name:'statistics'};if(p==='/profile/history')return{name:'history'};if(p==='/profile/settings')return{name:'settings'};if(p==='/upgrade')return{name:'upgrade'};return{name:'home'}};
  const q=s=>document.querySelector(s),visible=(el,on,display='')=>{if(!el)return;el.style.display=on?display:'none';el.setAttribute('aria-hidden',on?'false':'true')};
  const navigate=(path,replace=false)=>{const target=path.startsWith('/')?path:`/${path}`;if(normalize()!==normalize(target))(replace?history.replaceState:history.pushState).call(history,{},'',target);render()};
  let nativeCase=null;
  function closeAll(){['profilePage','settingsOverlay','statsOverlay','historyOverlay'].forEach(id=>visible(document.getElementById(id),false));const up=document.getElementById('edUpgrade2');if(up)up.classList.remove('open','closing');visible(document.getElementById('openPage'),false);document.body.classList.remove('case-route')}
  function chrome(on){visible(q('body > header'),on);visible(q('body > .top-line'),on);visible(q('body > .search-wrap'),on);visible(q('body > .live-drops-bar'),on)}
  function showCase(id){const page=document.getElementById('openPage');visible(q('body > main'),true);visible(q('main > .cases'),false);chrome(false);document.body.classList.add('case-route');window.__edRouteRenderingCase=true;try{nativeCase?.(id)}finally{window.__edRouteRenderingCase=false}visible(page,true,'flex')}
  function render(){const r=route();closeAll();chrome(true);if(r.name==='home'||r.name==='cases'){visible(q('body > main'),true);visible(q('main > .cases'),true);return}if(r.name==='case'){showCase(r.id);return}chrome(false);visible(q('body > main'),false);if(!window.state?.currentUser){navigate('/');setTimeout(()=>window.openAuth?.('login'),0);return}if(r.name==='profile'){window.openProfile?.();visible(document.getElementById('profilePage'),true,'flex')}else if(r.name==='statistics'){window.openStats?.();visible(document.getElementById('statsOverlay'),true,'flex')}else if(r.name==='history'){window.openHistory?.();visible(document.getElementById('historyOverlay'),true,'flex')}else if(r.name==='settings'){window.openSettings?.();visible(document.getElementById('settingsOverlay'),true,'flex')}else if(r.name==='upgrade'){window.openUpgradeMenu?.()}}
  function bridge(){if(nativeCase||typeof window.openCasePage!=='function')return;nativeCase=window.openCasePage;window.openCasePage=id=>window.__edRouteRenderingCase?nativeCase(id):navigate(`/case/${encodeURIComponent(id)}`);const oldClose=window.closePage;if(typeof oldClose==='function')window.closePage=()=>route().name==='case'?navigate('/'):oldClose()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b){e.preventDefault();e.stopImmediatePropagation();navigate(b.dataset.route);return}const back=e.target.closest('[data-back]');if(back){e.preventDefault();e.stopImmediatePropagation();navigate('/');return}const p=e.target.closest('#profileBtn');if(p&&window.state?.currentUser){e.preventDefault();e.stopImmediatePropagation();navigate('/profile')}},true);
  window.addEventListener('popstate',render);window.EmojiDropsRouter={navigate,render,route};window.openProfileRoute=()=>navigate('/profile');window.openUpgradeRoute=()=>navigate('/upgrade');window.openStatsRoute=()=>navigate('/profile/statistics');window.openHistoryRoute=()=>navigate('/profile/history');window.openSettingsRoute=()=>navigate('/profile/settings');
  const init=()=>{bridge();setTimeout(()=>{bridge();render()},0)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();