(()=>{'use strict';
/* Emoji Drops — non-invasive runtime QA. Read-only. */
function run(){const checks=[];const pass=(name,ok,detail='')=>checks.push({name,ok:!!ok,detail});
const catalog=typeof cases!=='undefined'?cases:{};const prices=typeof casePrices!=='undefined'?casePrices:{};const keys=Object.keys(catalog);pass('catalog loaded',keys.length>0,`${keys.length} cases`);pass('case catalog integrity',keys.length>=8,keys.join(', '));
let items=0,badItems=0;keys.forEach(k=>(catalog[k]||[]).forEach(x=>{items++;if(!x||!x.emoji||!x.rarity||!(Number(x.value)||Number(x.price)>0))badItems++}));pass('catalog items valid',badItems===0,`${items} items, ${badItems} invalid`);const priceBad=keys.filter(k=>!(Number(prices[k])>0));pass('case prices valid',priceBad.length===0,priceBad.join(', '));
const rarity={common:55,rare:27,epic:12,mythical:5,legendary:1};pass('rarity weights sum to 100',Object.values(rarity).reduce((a,b)=>a+b,0)===100);
const rtp=keys.map(k=>{const list=catalog[k]||[],counts={};list.forEach(x=>counts[x.rarity]=(counts[x.rarity]||0)+1);const ev=list.reduce((s,x)=>s+(rarity[x.rarity]||0)/100/(counts[x.rarity]||1)*(Number(x.value)||Number(x.price)||0),0);return{k,cost:Number(prices[k]),ev,rtp:Number(prices[k])?ev/Number(prices[k]):0}});pass('case RTP within economy QA band 82–99%',rtp.every(x=>x.rtp>=.82&&x.rtp<=.99),rtp.filter(x=>x.rtp<.82||x.rtp>.99).map(x=>`${x.k}:${(x.rtp*100).toFixed(1)}%`).join(', '));
['edAuthModal','edOpenModal','edWinModal','edProfileModal','edStatsModal','edSettingsModal','edUpgradeModal'].forEach(id=>pass(`modal #${id}`,!!document.getElementById(id)));['1.5','2','3','5'].forEach(m=>pass(`upgrade multiplier ×${m}`,!!document.querySelector(`#edUpgradeModal [data-ed-mult="${m}"]`)));['edUpgradeInventory','edTargets','edChance','edReels','edOpen'].forEach(id=>pass(`interactive surface #${id}`,!!document.getElementById(id)));const controls=['edLogin','edRegister','edSettings','edReward','edUpgrade','edStats','edLogout','edSellAll','edSave','edDelete','edFast','edDoUpgrade'];controls.forEach(id=>pass(`interactive control #${id}`,!!document.getElementById(id)));pass('modal close controls',document.querySelectorAll('[data-ed-close]').length>=7);pass('case cards mounted',document.querySelectorAll('[data-ed-case]').length===keys.length);
let storage=true;try{const k='__ed_qa__';localStorage.setItem(k,'1');storage=localStorage.getItem(k)==='1';localStorage.removeItem(k)}catch{storage=false}pass('localStorage writable',storage);
const scripts=[...document.scripts].map(s=>s.src).filter(Boolean);['functional-final.js','economy-balance.js','economy-sim-qa.js','runtime-hardening.js','transaction-guard.js','game-transaction-engine.js','transaction-serialization.js','runtime-action-bridge.js','case-upgrade-polish.js','motion-system.js','runtime-qa.js','final-quality-qa.js','runtime-final-qa.js'].forEach(x=>pass(`runtime script ${x}`,scripts.some(s=>s.includes(x))));pass('single authoritative engine script',scripts.filter(s=>s.includes('game-transaction-engine.js')).length===1);const bridge=window.__emojiDropsActionBridge;pass('authoritative action bridge active',bridge?.authoritative===true&&Number(bridge?.version||0)>=2,bridge?`v${bridge.version}`:'missing');const loader=window.__emojiDropsRuntimeLoader;pass('runtime loader complete',loader?.complete===true,loader?`v${loader.version}; failed=${loader.failed?.length||0}`:'missing');pass('runtime loader has no failed layers',Array.isArray(loader?.failed)&&loader.failed.length===0,loader?.failed?.join(', ')||'clean');const motion=window.__emojiDropsMotion;pass('motion system active',motion?.visualOnly===true&&Number(motion?.version||0)>=1,motion?`v${motion.version}`:'missing');
const perf=window.__emojiDropsPerf;pass('adaptive performance profile active',!!perf?.version);pass('performance profile sane',!!perf&&perf.reelItems>=18&&perf.reelItems<=56&&perf.reelTarget<perf.reelItems&&perf.reelDuration>=0&&perf.upgradeDuration>=0&&perf.liveLimit>=1&&perf.liveLimit<=10);pass('case reel timing tuned',!!perf&&perf.reelDuration===0||perf.reelDuration>=5000&&perf.reelDuration<=5500,perf?`${perf.reelDuration}ms`:'missing');pass('upgrade timing tuned',!!perf&&perf.upgradeDuration===0||perf.upgradeDuration>=4500&&perf.upgradeDuration<=5000,perf?`${perf.upgradeDuration}ms`:'missing');
pass('live strip mounted',!!document.querySelector('.live-section #liveContainer'));pass('live title hidden',!document.querySelector('.live-section .live-title')||getComputedStyle(document.querySelector('.live-section .live-title')).display==='none');pass('online dot mounted',!!document.querySelector('.online-dot'));pass('open cost hidden',!document.querySelector('#edOpenModal .open-cost'));pass('fast open control mounted',!!document.getElementById('edFast'));
const quality=window.__emojiDropsQualityQA;pass('final quality guard active',!!quality?.version);const serialization=window.__emojiDropsSerialization;pass('transaction serialization active',!!serialization?.version);pass('transaction serialization mode valid',serialization?.mode==='web-locks'||serialization?.mode==='engine-fallback');const ecoQA=window.__emojiDropsEconomyQA;pass('economy balancer active',!!window.__emojiDropsEconomy?.version);pass('economy target RTP',Math.abs(Number(window.__emojiDropsEconomy?.targetRTP||0)-.908)<.001);pass('economy statistical QA active',Number(ecoQA?.version||0)>=5);pass('economy statistical QA clean',Array.isArray(ecoQA?.errors)&&ecoQA.errors.length===0,ecoQA?.errors?.join('; ')||'clean');
const engine=window.__emojiDropsEngine;pass('transaction guard active',!!window.__emojiDropsTxGuard?.version);pass('transaction guard is recovery-only',window.__emojiDropsTxGuard?.mode==='legacy-recovery-only');pass('authoritative transaction engine active',!!engine?.version);pass('engine version hardened',Number(engine?.version||0)>=5);pass('engine cross-tab lock available',Number(engine?.lock?.ttl||0)>=10000);pass('engine has case entrypoint',typeof engine?.openCase==='function');pass('engine has upgrade entrypoint',typeof engine?.upgrade==='function');pass('engine starts idle',engine?.state?.busy===false);let scenario=null;try{scenario=engine?.qa?.()}catch(e){scenario={pass:false,error:String(e)}}pass('engine economy scenario QA',scenario?.pass===true,scenario?.error||'clean');
const duplicateIds=[...document.querySelectorAll('[id]')].map(x=>x.id).filter((id,i,a)=>id&&a.indexOf(id)!==i);pass('no duplicate DOM ids',duplicateIds.length===0);const buttons=[...document.querySelectorAll('button')];const unlabeled=buttons.filter(b=>!b.textContent.trim()&&!b.getAttribute('aria-label')&&!b.getAttribute('title')).length;pass('buttons have accessible names',unlabeled===0);const failed=checks.filter(x=>!x.ok);window.__emojiDropsQA={version:4,ok:failed.length===0,checks,failedCount:failed.length,rtp,ranAt:new Date().toISOString()};console.groupCollapsed(`Emoji Drops QA: ${failed.length?'FAIL':'PASS'} (${checks.length} checks)`);checks.forEach(x=>console[x.ok?'log':'error'](`${x.ok?'✓':'✗'} ${x.name}`,x.detail));console.groupEnd();return window.__emojiDropsQA}
const boot=()=>setTimeout(run,0);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
