(()=>{'use strict';
const VERSION='stable-polish-2';
const REWARD=250,REWARD_MS=15*60*1000,REWARD_KEY='emojiDrops.reward.v2';
function qs(s,r=document){return r.querySelector(s)}
function users(){try{const a=JSON.parse(localStorage.getItem('users')||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function saveUsers(a){localStorage.setItem('users',JSON.stringify(a))}
function currentEmail(){return localStorage.getItem('currentUser')||''}
function user(){const e=currentEmail();return users().find(x=>x.email===e)||null}
function syncHeader(){const u=user();const b=qs('#balance'),n=qs('#nickname');if(b)b.textContent=Math.round(Number(u?.balance??1000));if(n)n.textContent=u?.nickname||'Гость';syncRewardButton();}
function rewardState(){const key=REWARD_KEY+':'+(currentEmail()||'guest');try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}
function leftMs(){return Math.max(0,Number(rewardState().nextAt||0)-Date.now())}
function clock(ms){const s=Math.ceil(ms/1000),m=Math.floor(s/60),q=s%60;return `${String(m).padStart(2,'0')}:${String(q).padStart(2,'0')}`}
function syncRewardButton(){const b=qs('#rewardHeader');if(!b)return;const u=user(),left=leftMs();b.disabled=!u||left>0;b.textContent=!u?'🎁 +250₽':left>0?`⏱ ${clock(left)}`:'🎁 +250₽'}
function claimReward(){const u=user();if(!u){if(typeof show==='function')show('edAuthModal');return}if(leftMs()>0)return;u.balance=Math.max(0,Number(u.balance)||0)+REWARD;u.stats=u.stats||{opened:0,upgrades:0,spent:0,received:0};u.stats.received=Number(u.stats.received)||0;u.stats.received+=REWARD;saveUsers(users().map(x=>x.email===u.email?u:x));localStorage.setItem(REWARD_KEY+':'+u.email,JSON.stringify({nextAt:Date.now()+REWARD_MS}));syncHeader();if(typeof profileSync==='function')profileSync()}
function installReward(){document.addEventListener('click',e=>{const b=e.target.closest('#rewardHeader,#edReward');if(!b)return;e.preventDefault();e.stopImmediatePropagation();claimReward()},true);window.setInterval(syncRewardButton,1000)}
function parseChance(){const el=qs('#edChance');if(!el)return 0;const m=(el.textContent||'').match(/([0-9]+(?:\.[0-9]+)?)\s*%/);return m?Math.max(0,Math.min(100,Number(m[1]))):0}
function setWheel(chance,spinning=false,outcome=''){const c=qs('.ed-final-wheel-circle');if(!c)return;c.style.setProperty('--ed-chance',chance+'%');c.classList.toggle('ed-stable-spin',spinning);c.classList.toggle('ed-win',outcome==='win');c.classList.toggle('ed-lose',outcome==='lose');c.setAttribute('aria-label','Шанс '+chance.toFixed(1)+'%')}
function wheel(){const c=qs('.ed-final-wheel-circle');if(!c)return;setWheel(parseChance(),false);if(!window.MutationObserver)return;const el=qs('#edChance');if(el)new MutationObserver(()=>setWheel(parseChance(),c.classList.contains('ed-stable-spin'))).observe(el,{childList:true,subtree:true,characterData:true})}
function upgradeAnimation(){document.addEventListener('click',e=>{const b=e.target.closest('#edDoUpgrade');if(!b)return;const c=qs('.ed-final-wheel-circle');if(!c)return;setWheel(parseChance(),true);window.setTimeout(()=>{const text=(qs('#edChance')?.textContent||'').toLowerCase();setWheel(parseChance(),false,text.includes('усп')?'win':text.includes('неуда')?'lose':'')},5200)},true)}
function polishCSS(){if(qs('#stable-polish-css'))return;const s=document.createElement('style');s.id='stable-polish-css';s.textContent=`html{scroll-behavior:smooth}.case-card{transition:transform .22s cubic-bezier(.2,.8,.2,1),border-color .22s,box-shadow .22s,filter .22s;will-change:transform}.case-card:hover{box-shadow:0 18px 45px #0008;filter:brightness(1.04)}.case-card:active{transform:translateY(-1px) scale(.99)!important}.primary,.secondary,.profile-btn,.profile-top,.reward-top,.close,.amount,.ed-final-item-btn,.ed-final-mults button{transition:transform .16s ease,border-color .18s ease,background .18s ease,box-shadow .18s ease}.primary:active,.secondary:active,.profile-btn:active,.profile-top:active,.reward-top:active,.close:active,.amount:active,.ed-final-item-btn:active,.ed-final-mults button:active{transform:scale(.98)}.reward-top:disabled{opacity:.6;cursor:not-allowed}.modal{opacity:0;transition:opacity .18s ease}.modal.show{opacity:1}.modal .panel{transform:translateY(10px) scale(.985);opacity:0;transition:transform .22s cubic-bezier(.2,.8,.2,1),opacity .18s ease}.modal.show .panel{transform:none;opacity:1}.live-section{position:fixed;left:0;right:0;bottom:0;z-index:45;margin:0;padding:8px 24px 10px;background:linear-gradient(180deg,#09090900,#090909f2 24%);pointer-events:none}.live-section>*{pointer-events:auto}.live-title{display:none}.live-container{max-width:1240px;margin:0 auto;padding:6px 0 2px;mask-image:linear-gradient(90deg,transparent,#000 3%,#000 97%,transparent)}main{padding-bottom:105px}.ed-final-wheel-circle{--ed-chance:0%;position:relative;overflow:visible;background:conic-gradient(from -90deg,#ff7b00 0 var(--ed-chance),#262626 var(--ed-chance) 100%)!important;border:3px solid #ff7b00!important;box-shadow:0 0 30px #ff7b0033!important;transform:none!important;animation:none}.ed-final-wheel-circle:before{content:'➤';position:absolute;left:50%;top:50%;width:74px;height:74px;display:grid;place-items:center;border-radius:50%;background:#111;color:#fff;font-size:34px;line-height:1;transform:translate(-50%,-50%) rotate(0deg);transform-origin:center;transition:transform .35s cubic-bezier(.2,.8,.2,1);z-index:2;filter:drop-shadow(0 3px 8px #000)}.ed-final-wheel-circle.ed-stable-spin:before{animation:stableArrow 5s cubic-bezier(.15,.75,.2,1) infinite}.ed-final-wheel-circle.ed-win{box-shadow:0 0 36px #31d15866!important}.ed-final-wheel-circle.ed-lose{box-shadow:0 0 36px #ff453a55!important}@keyframes stableArrow{0%{transform:translate(-50%,-50%) rotate(-90deg)}72%{transform:translate(-50%,-50%) rotate(1510deg)}100%{transform:translate(-50%,-50%) rotate(1440deg)}}@media(max-width:700px){.live-section{padding-left:12px;padding-right:12px}.live-drop{flex-basis:150px}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}}`;document.head.appendChild(s)}
function repairStorage(){try{if(!Array.isArray(JSON.parse(localStorage.getItem('users')||'[]')))localStorage.setItem('users','[]')}catch{localStorage.setItem('users','[]')}}
function boot(){repairStorage();polishCSS();installReward();syncHeader();window.setTimeout(wheel,0);upgradeAnimation();window.__emojiDropsStable={version:VERSION,core:'data+economy+functional',optionalLayersDisabled:true,rewardCooldown:REWARD_MS}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();