(()=>{'use strict';
const V='20260901-15';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const num=v=>{const s=String(v??'').replace(/\s/g,'').replace(/[^0-9.,-]/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const visible=el=>!!el&&getComputedStyle(el).display!=='none'&&getComputedStyle(el).visibility!=='hidden';
const balance=()=>num($('#balance')?.textContent||window.balance||0);
const itemPrice=el=>num(el?.dataset?.price||el?.querySelector('[data-price]')?.dataset?.price||el?.querySelector('.u-value,.case-price,small')?.textContent||0);
function css(){if($('#ed-stability-final-v15'))return;const s=document.createElement('style');s.id='ed-stability-final-v15';s.textContent=`
html,body,#app,#root{width:100%;max-width:none;overflow-x:hidden}
main{width:100%!important;max-width:none!important;padding-left:34px!important;padding-right:34px!important}
.home-divider{position:relative;top:-2px!important;margin-bottom:20px!important}
.cases{width:100%!important;max-width:none!important;margin-top:5px!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:18px!important}
.live-section{position:fixed!important;left:0!important;right:0!important;bottom:0!important;width:100vw!important;max-width:none!important;margin:0!important;padding-left:34px!important;padding-right:0!important;box-sizing:border-box!important}
.live-title,.live-container{width:100%!important;max-width:none!important;margin-left:0!important;margin-right:0!important}.live-container{padding-right:34px!important}
.best-wrap button,.best-wrap [data-action*="sell"],.best-wrap [onclick*="sell"],.best-wrap [onclick*="Sell"]{display:none!important}.best-wrap{overflow:visible!important}.best{max-width:100%!important;overflow:visible!important}
.ed-disabled-case{filter:saturate(.55);opacity:.58!important}.ed-affordability{pointer-events:none!important}
.upgrade-target.is-invalid{opacity:.22!important;filter:grayscale(.9)!important;pointer-events:none!important;cursor:not-allowed!important}.upgrade-target.is-valid{opacity:1!important}
.upgrade-wheel-pro{position:relative;width:clamp(190px,22vw,260px);aspect-ratio:1;border-radius:50%;background:conic-gradient(from -90deg,#37d98a 0 var(--win,0%),#ff4d5f var(--win,0%) 100%);border:8px solid #202020;box-shadow:0 0 0 2px #ffffff12,0 20px 55px #0009,inset 0 0 35px #000;isolation:isolate;will-change:auto}
.upgrade-wheel-pro:before{content:'';position:absolute;inset:9px;border-radius:50%;border:1px solid #ffffff35;box-shadow:inset 0 0 0 1px #0008}
.upgrade-wheel-pro:after{content:'';position:absolute;inset:24%;border-radius:50%;background:radial-gradient(circle,#191919 0,#0d0d0d 68%,#090909 100%);border:2px solid #ff922d;box-shadow:0 0 28px #ff7b0050}
.upgrade-wheel-pro .pro-center{position:absolute;z-index:5;inset:0;display:grid;place-items:center;color:#fff;font-size:clamp(20px,3vw,30px);font-weight:1000;font-variant-numeric:tabular-nums;text-shadow:0 2px 10px #000}
.upgrade-wheel-pro .pro-pointer{position:absolute;z-index:8;left:50%;top:-19px;width:0;height:0;border-left:12px solid transparent;border-right:12px solid transparent;border-top:29px solid #ff9a2e;filter:drop-shadow(0 0 8px #ff7b00);transform:translateX(-50%) rotate(0deg);transform-origin:50% calc(50% + 130px)}
.upgrade-wheel-pro.spinning .pro-pointer{animation:edUpgradeSpinV15 3.8s cubic-bezier(.12,.78,.08,1) forwards}
.upgrade-wheel-pro.win{box-shadow:0 0 0 2px #37d98a88,0 0 55px #37d98a44,inset 0 0 35px #000}.upgrade-wheel-pro.loss{box-shadow:0 0 0 2px #ff4d5f88,0 0 45px #ff4d5f22,inset 0 0 35px #000}
@keyframes edUpgradeSpinV15{0%{transform:translateX(-50%) rotate(0deg)}12%{transform:translateX(-50%) rotate(95deg)}72%{transform:translateX(-50%) rotate(calc(var(--stop-angle,1080deg) - 55deg))}100%{transform:translateX(-50%) rotate(var(--stop-angle,1080deg))}}
@media(max-width:1100px){main{padding-left:24px!important;padding-right:24px!important}.cases{grid-template-columns:repeat(2,minmax(0,1fr))!important}.live-section{padding-left:24px!important}.live-container{padding-right:24px!important}}
@media(max-width:600px){main{padding-left:12px!important;padding-right:12px!important}.cases{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:12px!important}.live-section{padding-left:12px!important}.live-container{padding-right:12px!important}.upgrade-wheel-pro{width:180px}.upgrade-wheel-pro .pro-pointer{transform-origin:50% calc(50% + 105px)}}
@media(prefers-reduced-motion:reduce){.upgrade-wheel-pro.spinning .pro-pointer{animation:none!important}}
`;document.head.appendChild(s)}
function profileLive(){const p=$('#profileModal');const l=$('.live-section');if(l)l.style.display=visible(p)?'none':''}
function removeBestSell(){ $$('.best-wrap button,.best-wrap [data-action],.best-wrap [onclick]').forEach(b=>{const t=(b.textContent||'').toLowerCase();if(t.includes('продать')||String(b.getAttribute('data-action')||'').toLowerCase().includes('sell')||String(b.getAttribute('onclick')||'').toLowerCase().includes('sell'))b.remove()}) }
function syncCases(){
 $$('.case-tile,.case-card').forEach(tile=>{const price=itemPrice(tile);const btn=tile.querySelector('button,.case-open,.open-case,[data-action="open-case"],[data-action="open"]');if(!btn||!price)return;const ok=balance()+0.000001>=price;btn.disabled=!ok;btn.setAttribute('aria-disabled',String(!ok));btn.classList.toggle('ed-affordability',!ok);tile.classList.toggle('ed-disabled-case',!ok)});
 const panel=$('.panel.show,.modal.show');if(!panel)return;const cost=num($('.open-cost',panel)?.textContent||0);const openBtn=$('.reel-actions .primary,[data-action="open"]',panel);if(openBtn&&cost){const ok=balance()+0.000001>=cost;openBtn.disabled=!ok;openBtn.setAttribute('aria-disabled',String(!ok));const root=openBtn.closest('.panel-body')||panel;$$('*',root).forEach(e=>{if(e.children.length)return;const t=e.textContent.trim();if(t==='Количество открытий'||t==='Недостаточно средств'||/^\d+(?:[.,]\d+)?₽$/.test(t))e.style.display=ok?'':'none'})}}
function upgradeState(){
 const panel=$('#upgradeModal')||$('.upgrade-modal')||$('.upgrade-runtime')?.closest('.panel');if(!panel)return;
 const source=panel.querySelector('.upgrade-slot:first-child .u-value,.source .u-value');const sv=itemPrice(source);const mult=num(panel.querySelector('.upgrade-mult.active')?.textContent)||2;const max=sv*mult;
 $$('.upgrade-target',panel).forEach(t=>{const tv=itemPrice(t);const valid=sv>0&&tv>sv&&tv<=max+0.000001;t.classList.toggle('is-invalid',!valid);t.classList.toggle('is-valid',valid);t.setAttribute('aria-disabled',String(!valid));if(!valid)t.classList.remove('selected')});
 const selected=$('.upgrade-target.selected',panel);const tv=itemPrice(selected);const chance=selected&&tv>sv?Math.max(0,Math.min(100,(sv/tv)*100)):0;const ch=$('.upgrade-chance',panel);if(ch)ch.textContent=`Шанс: ${chance.toFixed(chance<10?2:1)}%`;
 let wheel=$('.upgrade-wheel-pro',panel);if(!wheel){const old=$('.upgrade-arrow,.upgrade-wheel',panel);if(old){wheel=document.createElement('div');wheel.className='upgrade-wheel-pro';wheel.innerHTML='<div class="pro-pointer"></div><div class="pro-center">0%</div>';old.replaceWith(wheel)}}
 if(wheel){wheel.style.setProperty('--win',`${chance}%`);const c=$('.pro-center',wheel);if(c)c.textContent=`${chance.toFixed(chance<10?1:0)}%`;}}
function upgradeClick(e){const target=e.target.closest('.upgrade-target');if(target){const panel=target.closest('.panel')||$('#upgradeModal');if(target.classList.contains('is-invalid')){e.preventDefault();e.stopImmediatePropagation();return}setTimeout(()=>upgradeState(),0)}const submit=e.target.closest('.upgrade-submit');if(!submit)return;const panel=submit.closest('.panel')||$('#upgradeModal');const targetNow=$('.upgrade-target.selected',panel);if(!targetNow||targetNow.classList.contains('is-invalid')){e.preventDefault();e.stopImmediatePropagation();return}const wheel=$('.upgrade-wheel-pro',panel);const chance=num($('.upgrade-chance',panel)?.textContent);if(!wheel||chance<=0)return;const win=Math.random()*100<chance;const start=720;const sector=win?Math.random()*chance*3.6:chance*3.6+Math.random()*(100-chance)*3.6;const stop=start+sector;wheel.style.setProperty('--stop-angle',`${stop}deg`);wheel.classList.remove('win','loss','spinning');void wheel.offsetWidth;wheel.classList.add('spinning');setTimeout(()=>wheel.classList.add(win?'win':'loss'),3900)}
function bind(){document.addEventListener('click',e=>{removeBestSell();profileLive();syncCases();upgradeState();upgradeClick(e)},true);window.addEventListener('storage',()=>{syncCases();upgradeState()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){syncCases();upgradeState();profileLive()}});setInterval(()=>{if(!document.hidden){profileLive();syncCases();upgradeState()}},500)}
css();bind();requestAnimationFrame(()=>{removeBestSell();profileLive();syncCases();upgradeState()});window.addEventListener('emoji-drops-ready',()=>{removeBestSell();profileLive();syncCases();upgradeState()});
})();