(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>Number(String(v??0).replace(/[^0-9.,]/g,'').replace(',','.'))||0;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const user=()=>window.state?.currentUser||null;
const rarityColor=i=>window.rarities?.[i?.rarity]?.color||'#ff7b00';
const save=()=>window.saveUsers?.();
const saveStats=()=>window.saveStats?.();
const gameStats=()=>window.state?.stats||(window.state.stats={opened:0,upgrades:0,spent:0,received:0,withdrawnItems:0});
function history(type,title,item,value){const u=user();if(!u)return;u.history=Array.isArray(u.history)?u.history:[];u.history.unshift({type,title,item:item?.emoji||'',value:value??item?.price??'',at:Date.now()});u.history=u.history.slice(0,100);save();}
function best(){const u=user(),e=$('#bestDropEmoji'),r=$('#bestDropRarity'),p=$('#bestDropPrice');if(!e||!r)return;let b=u?.bestDrop||null;for(const i of u?.inventory||[])if(!b||money(i.price)>money(b.price))b={...i};if(!b){e.textContent='🏆';r.textContent='Нет дропа';if(p)p.textContent='';return;}u.bestDrop={...b};e.textContent=b.emoji;r.textContent=String(b.rarity||'common').toUpperCase();r.style.color=rarityColor(b);if(p)p.textContent=b.price||'';save();}
function renderHistory(){const box=$('#historyList');if(!box)return;const list=user()?.history||[],icons={open:'📦',sell:'💰',upgrade:'⬆️'};box.innerHTML='';if(!list.length){box.innerHTML='<div class="ed-empty">История пока пуста</div>';return;}for(const x of list){const d=document.createElement('div');d.className='history-item';d.innerHTML=`<div class="history-icon">${icons[x.type]||'🎁'}</div><div><b>${x.title}</b><div class="history-sub">${x.item||''}</div></div><div><b>${x.value||''}</b><div class="history-time">${new Date(x.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</div></div>`;box.appendChild(d);}}
window.openHistory=()=>{if(!user())return window.openAuth?.('login');renderHistory();const x=$('#historyOverlay');if(x)x.style.display='flex';};window.closeHistory=()=>{const x=$('#historyOverlay');if(x)x.style.display='none';};
window.openSettings=()=>{if(!user())return window.openAuth?.('login');const x=$('#settingsOverlay');if(x)x.style.display='flex';};window.closeSettings=()=>{const x=$('#settingsOverlay');if(x)x.style.display='none';};
window.updateStatsUI=()=>{const s=gameStats(),set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v;};set('openedCases',s.opened||0);set('upgradeCount',s.upgrades||0);set('spentAmount',`${Math.round(s.spent||0)}₽`);set('receivedAmount',`${Math.round(s.received||0)}₽`);set('withdrawItems',s.withdrawnItems||0);};
window.openStats=()=>{if(!user())return window.openAuth?.('login');window.updateStatsUI();const x=$('#statsOverlay');if(x)x.style.display='flex';};window.closeStats=()=>{const x=$('#statsOverlay');if(x)x.style.display='none';};
window.renderInventory=()=>{const g=$('#inventoryGrid');if(!g)return;const inv=user()?.inventory||[];g.innerHTML='';if(!inv.length){g.innerHTML='<div class="ed-empty">Инвентарь пуст<br><small>Откройте кейс, чтобы получить первый предмет.</small></div>';return;}inv.forEach((i,n)=>{const c=document.createElement('div');c.className='ed-inventory-card';c.style.borderColor=rarityColor(i);c.innerHTML=`<div class="ed-inventory-emoji">${i.emoji}</div><b>${String(i.rarity||'common').toUpperCase()}</b><b>${i.price||''}</b><button class="settings-action-btn">Продать</button>`;c.querySelector('button').onclick=()=>sell(n);g.appendChild(c);});};
function sell(n){const u=user(),i=u?.inventory?.[n];if(!i)return;u.inventory.splice(n,1);const v=money(i.price),s=gameStats();window.state.balance=(window.state.balance||0)+v;u.balance=window.state.balance;s.withdrawnItems=(s.withdrawnItems||0)+1;s.received=(s.received||0)+v;history('sell','Продан предмет',i,`+${Math.round(v)}₽`);save();saveStats();window.updateBalanceUI?.();window.renderInventory();best();}
window.openProfile=()=>{if(!user())return window.openAuth?.('login');const p=$('#profilePage');if(!p)return;p.style.display='block';p.setAttribute('aria-hidden','false');$('#profileName').textContent=user().nickname||'Игрок';$('#profileBalance').textContent=window.state.balance??user().balance??0;window.renderInventory();window.updateStatsUI();best();window.scrollTo({top:0,behavior:'smooth'});};window.closeProfile=()=>{const p=$('#profilePage');if(p){p.style.display='none';p.setAttribute('aria-hidden','true');}};
function sync(){const u=user();if(!u)return;u.balance=window.state.balance;save();window.updateBalanceUI?.();}
function lane(track,win){const pool=window.state.currentCase||[];track.innerHTML='';const targetIndex=34;for(let n=0;n<50;n++){const i=n===targetIndex?win:(window.getRandomByChance?window.getRandomByChance(pool):pool[Math.floor(Math.random()*pool.length)]);const e=document.createElement('div');e.className='item';e.textContent=i?.emoji||'❔';e.style.borderColor=rarityColor(i);if(n===targetIndex)e.dataset.target='1';track.appendChild(e);}}
window.createRoulettes=()=>{const c=$('#multiRouletteContainer');if(!c)return;c.innerHTML='';const amount=Math.max(1,Math.min(10,Number(window.state?.openAmount)||1));for(let n=0;n<amount;n++){const l=document.createElement('div');l.className='multi-roulette';l.dataset.lane=String(n);l.innerHTML='<div class="new-pointer" aria-hidden="true"></div><div class="multi-track"></div>';c.appendChild(l);const t=l.querySelector('.multi-track');const pool=window.state?.currentCase||[];for(let k=0;k<50;k++){const i=window.getRandomByChance?.(pool)||{};const e=document.createElement('div');e.className='item';e.textContent=i.emoji||'❔';e.style.borderColor=rarityColor(i);t.appendChild(e);}}};
async function spin(wins,fast){const lanes=$$('.multi-roulette').slice(0,wins.length);for(let n=0;n<wins.length;n++){const l=lanes[n];if(!l)continue;const t=l.querySelector('.multi-track');lane(t,wins[n]);const target=t.querySelector('[data-target]');if(!target)continue;const x=Math.round(l.clientWidth/2-(target.offsetLeft+target.offsetWidth/2));t.style.transition='none';t.style.transform='translate3d(0,0,0)';void t.offsetWidth;await new Promise(requestAnimationFrame);const duration=fast?220:2500+n*35;t.style.transition=`transform ${duration}ms cubic-bezier(.06,.72,.12,1)`;t.style.transform=`translate3d(${x}px,0,0)`;}await wait(fast?280:2860);$$('[data-target]').forEach(x=>x.classList.add('ed-lane-target'));}
async function openCaseFlow(count,fast=false){const s=window.state;if(!s||s.isSpinning)return;if(!s.selectedCase)return alert('Выберите кейс');if(!user())return window.openAuth?.('login');count=Math.max(1,Math.min(10,Number(count)||1));const unit=window.casePrices?.[s.selectedCase]||0,cost=unit*count;if(s.balance<cost)return alert('Недостаточно средств');s.isSpinning=true;s.openAmount=count;window.createRoulettes();s.balance-=cost;sync();const wins=Array.from({length:count},()=>window.getRandomByChance(s.currentCase));try{await spin(wins,fast);const u=user();u.inventory=u.inventory||[];const stats=gameStats();for(const i of wins){u.inventory.push({...i});history('open','Открыт кейс',i,i.price);window.addLiveDrop(u.nickname||'Игрок',i);if(!u.bestDrop||money(i.price)>money(u.bestDrop.price))u.bestDrop={...i};}stats.opened=(stats.opened||0)+count;stats.spent=(stats.spent||0)+cost;save();saveStats();window.renderInventory();best();s.winQueue=wins.slice();window.showNextWin();}finally{s.isSpinning=false;}}
window.openCase=(count=window.state?.openAmount||1)=>openCaseFlow(count,false);window.fastOpenCase=()=>openCaseFlow(window.state?.openAmount||1,true);
window.showNextWin=()=>{const s=window.state;if(!s?.winQueue?.length){s.currentWin=null;return;}const i=s.winQueue.shift();s.currentWin=i;$('#winEmoji').textContent=i.emoji;const r=$('#winRarity');r.textContent=String(i.rarity||'common').toUpperCase();r.style.color=rarityColor(i);$('#winPrice').textContent=i.price||'';const p=$('#winPopup');p.style.display='flex';p.className=`win-popup ed-win-enter ed-rarity-${i.rarity||'common'}`;};window.closeWin=()=>{const p=$('#winPopup');if(p)p.style.display='none';};window.takeWin=()=>{window.closeWin();window.showNextWin();};window.sellWin=()=>{const s=window.state,i=s?.currentWin,u=user();if(!i||!u)return;const n=u.inventory.findIndex(x=>x.emoji===i.emoji&&x.rarity===i.rarity&&x.price===i.price);if(n>=0)sell(n);window.closeWin();window.showNextWin();};
window.addLiveDrop=(name,i)=>{const c=$('#liveContainer');if(!c||!i)return;const before=new Map([...c.children].map(e=>[e,e.getBoundingClientRect()]));const d=document.createElement('div');d.className=`live-drop ${i.rarity||''}`;d.style.borderColor=rarityColor(i);d.innerHTML=`<div class="live-emoji">${i.emoji}</div><div class="live-info"><div class="live-user">${name||'Игрок'}</div><div class="live-rarity" style="color:${rarityColor(i)}">${String(i.rarity||'common').toUpperCase()}</div></div>`;c.prepend(d);while(c.children.length>25)c.lastElementChild.remove();requestAnimationFrame(()=>{for(const e of c.children){const old=before.get(e);if(!old||e===d)continue;const now=e.getBoundingClientRect(),dx=old.left-now.left,dy=old.top-now.top;e.style.transition='none';e.style.transform=`translate3d(${dx}px,${dy}px,0)`;requestAnimationFrame(()=>{e.style.transition='transform .42s cubic-bezier(.22,1,.36,1)';e.style.transform='';});}d.classList.add('ed-live-enter');});};window.createLiveDrop=window.addLiveDrop;
function boot(){const input=$('#searchInput');if(input){input.value='';input.autocomplete='off';input.name='case_search_query';input.type='search';input.setAttribute('data-form-type','other');input.addEventListener('focus',()=>{if(input.value)input.value='';},{once:true});}const fast=$('.fast-btn');if(fast)fast.onclick=window.fastOpenCase;document.addEventListener('click',e=>{const b=e.target.closest('.amount-btn');if(!b||!window.state)return;const n=Number(b.dataset.amount||b.textContent);if(n>=1&&n<=10){window.state.openAmount=n;$$('.amount-btn').forEach(x=>x.classList.toggle('active',x===b));window.createRoulettes();window.updateOpenPrice?.();}});}
boot();
})();