(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=v=>Number(String(v??0).replace(/[^0-9.,]/g,'').replace(',','.'))||0,wait=ms=>new Promise(r=>setTimeout(r,ms));
const user=()=>window.state?.currentUser||null,rarityColor=i=>window.rarities?.[i?.rarity]?.color||'#ff7b00';
const save=()=>window.saveUsers?.(),saveStats=()=>window.saveStats?.();
function history(type,title,item,value){const u=user();if(!u)return;u.history=Array.isArray(u.history)?u.history:[];u.history.unshift({type,title,item:item?.emoji||'',value:value??item?.price??'',at:Date.now()});u.history=u.history.slice(0,100);save();}
function best(){const u=user(),e=$('#bestDropEmoji'),r=$('#bestDropRarity'),p=$('#bestDropPrice');if(!e||!r)return;let b=u?.bestDrop||null;for(const i of u?.inventory||[])if(!b||money(i.price)>money(b.price))b={...i};if(!b){e.textContent='🏆';r.textContent='Нет дропа';if(p)p.textContent='';return;}u.bestDrop={...b};e.textContent=b.emoji;r.textContent=String(b.rarity).toUpperCase();r.style.color=rarityColor(b);if(p)p.textContent=b.price||'';save();}
function renderHistory(){const box=$('#historyList');if(!box)return;const list=user()?.history||[],icons={open:'📦',sell:'💰',upgrade:'⬆️'};box.innerHTML=list.length?'':'<div class="ed-empty">История пока пуста</div>';list.forEach(x=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<div class="history-icon">${icons[x.type]||'🎁'}</div><div><b>${x.title}</b><div class="history-sub">${x.item||''}</div></div><div><b>${x.value||''}</b><div class="history-time">${new Date(x.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</div></div>`;box.appendChild(d);});}
window.openHistory=()=>{if(!user())return window.openAuth?.('login');renderHistory();$('#historyOverlay').style.display='flex';};window.closeHistory=()=>$('#historyOverlay').style.display='none';
window.openSettings=()=>{if(!user())return window.openAuth?.('login');$('#settingsOverlay').style.display='flex';};window.closeSettings=()=>$('#settingsOverlay').style.display='none';
window.updateStatsUI=()=>{const s=window.state?.stats||{},set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v;};set('openedCases',s.opened||0);set('upgradeCount',s.upgrades||0);set('spentAmount',`${Math.round(s.spent||0)}₽`);set('receivedAmount',`${Math.round(s.received||0)}₽`);set('withdrawItems',s.withdrawnItems||0);};window.openStats=()=>{if(!user())return window.openAuth?.('login');window.updateStatsUI();$('#statsOverlay').style.display='flex';};window.closeStats=()=>$('#statsOverlay').style.display='none';
window.renderInventory=()=>{const g=$('#inventoryGrid');if(!g)return;const inv=user()?.inventory||[];g.innerHTML='';if(!inv.length){g.innerHTML='<div class="ed-empty">Инвентарь пуст<br><small>Откройте кейс, чтобы получить первый предмет.</small></div>';return;}inv.forEach((i,n)=>{const c=document.createElement('div');c.className='ed-inventory-card';c.style.borderColor=rarityColor(i);c.innerHTML=`<div class="ed-inventory-emoji">${i.emoji}</div><b>${String(i.rarity).toUpperCase()}</b><b>${i.price||''}</b><button class="settings-action-btn">Продать</button>`;c.querySelector('button').onclick=()=>sell(n);g.appendChild(c);});};
function sell(n){const u=user(),i=u?.inventory?.[n];if(!i)return;u.inventory.splice(n,1);const v=money(i.price);window.state.balance=(window.state.balance||0)+v;u.balance=window.state.balance;window.state.stats.withdrawnItems=(window.state.stats.withdrawnItems||0)+1;window.state.stats.received=(window.state.stats.received||0)+v;history('sell','Продан предмет',i,`+${Math.round(v)}₽`);save();saveStats();window.updateBalanceUI?.();window.renderInventory();best();}
window.openProfile=()=>{if(!user())return window.openAuth?.('login');const p=$('#profilePage');p.style.display='block';$('#profileName').textContent=user().nickname||'Игрок';$('#profileBalance').textContent=window.state.balance||user().balance||0;window.renderInventory();window.updateStatsUI();best();};window.closeProfile=()=>$('#profilePage').style.display='none';
function sync(){const u=user();if(!u)return;u.balance=window.state.balance;save();window.updateBalanceUI?.();}
function lane(track,win){const pool=window.state.currentCase||[];track.innerHTML='';for(let n=0;n<46;n++){const i=n===32?win:(window.getRandomByChance?window.getRandomByChance(pool):pool[Math.floor(Math.random()*pool.length)]);const e=document.createElement('div');e.className='item';e.textContent=i?.emoji||'❔';e.style.borderColor=rarityColor(i);if(n===32)e.dataset.target='1';track.appendChild(e);}}
window.createRoulettes=()=>{const c=$('#multiRouletteContainer');if(!c)return;c.innerHTML='';for(let n=0;n<(window.state?.openAmount||1);n++){const l=document.createElement('div');l.className='multi-roulette';l.innerHTML='<div class="new-pointer"></div><div class="multi-track"></div>';c.appendChild(l);const t=l.querySelector('.multi-track');for(let k=0;k<46;k++){const i=window.getRandomByChance?.(window.state.currentCase)||{};const e=document.createElement('div');e.className='item';e.textContent=i.emoji||'❔';e.style.borderColor=rarityColor(i);t.appendChild(e);}}};
async function spin(wins,fast){const lanes=$$('.multi-roulette');for(let n=0;n<wins.length;n++){const l=lanes[n];if(!l)continue;const t=l.querySelector('.multi-track');lane(t,wins[n]);const target=t.querySelector('[data-target]');const x=l.clientWidth/2-(target.offsetLeft+target.offsetWidth/2);t.style.transition='none';t.style.transform='translate3d(0,0,0)';await new Promise(requestAnimationFrame);t.style.transition=`transform ${fast?180:2200}ms cubic-bezier(.08,.72,.12,1)`;t.style.transform=`translate3d(${x}px,0,0)`;}await wait(fast?240:2260);$$('[data-target]').forEach(x=>x.classList.add('ed-lane-target'));}
window.openCase=async(count=window.state?.openAmount||1)=>{const s=window.state;if(!s||s.isSpinning)return;if(!s.selectedCase)return alert('Выберите кейс');if(!user())return window.openAuth?.('login');count=Math.max(1,Math.min(10,Number(count)||1));const cost=(window.casePrices?.[s.selectedCase]||0)*count;if(s.balance<cost)return alert('Недостаточно средств');s.isSpinning=true;s.openAmount=count;window.createRoulettes();s.balance-=cost;sync();const wins=Array.from({length:count},()=>window.getRandomByChance(s.currentCase));await spin(wins,false);user().inventory=user().inventory||[];wins.forEach(i=>{user().inventory.push({...i});history('open','Открыт кейс',i,i.price);window.addLiveDrop(user().nickname||'Игрок',i);if(!user().bestDrop||money(i.price)>money(user().bestDrop.price))user().bestDrop={...i};});s.stats.opened=(s.stats.opened||0)+count;s.stats.spent=(s.stats.spent||0)+cost;save();saveStats();window.renderInventory();best();s.winQueue=wins.slice();s.isSpinning=false;window.showNextWin();};
window.fastOpenCase=()=>window.openCase(window.state?.openAmount||1);
window.showNextWin=()=>{const s=window.state;if(!s?.winQueue?.length){s.currentWin=null;return;}const i=s.winQueue.shift();s.currentWin=i;$('#winEmoji').textContent=i.emoji;const r=$('#winRarity');r.textContent=String(i.rarity).toUpperCase();r.style.color=rarityColor(i);$('#winPrice').textContent=i.price||'';const p=$('#winPopup');p.style.display='flex';p.className=`win-popup ed-win-enter ed-rarity-${i.rarity}`;};window.closeWin=()=>$('#winPopup').style.display='none';window.takeWin=()=>{window.closeWin();window.showNextWin();};window.sellWin=()=>{const s=window.state,i=s?.currentWin,u=user();if(!i||!u)return;const n=u.inventory.findIndex(x=>x.emoji===i.emoji&&x.rarity===i.rarity&&x.price===i.price);if(n>=0)sell(n);window.closeWin();window.showNextWin();};
window.addLiveDrop=(name,i)=>{const c=$('#liveContainer');if(!c||!i)return;const old=[...c.children].map(e=>[e,e.getBoundingClientRect()]);const d=document.createElement('div');d.className=`live-drop ${i.rarity}`;d.style.borderColor=rarityColor(i);d.innerHTML=`<div class="live-emoji">${i.emoji}</div><div class="live-info"><div class="live-user">${name||'Игрок'}</div><div class="live-rarity" style="color:${rarityColor(i)}">${String(i.rarity).toUpperCase()}</div></div>`;c.prepend(d);while(c.children.length>25)c.lastElementChild.remove();requestAnimationFrame(()=>{[...c.children].forEach(e=>{const b=old.find(x=>x[0]===e)?.[1];if(!b)return;const now=e.getBoundingClientRect(),dx=b.left-now.left;e.style.transition='none';e.style.transform=`translate3d(${dx}px,0,0)`;requestAnimationFrame(()=>{e.style.transition='transform .42s cubic-bezier(.22,1,.36,1)';e.style.transform='';});});d.classList.add('ed-live-enter');});};window.createLiveDrop=window.addLiveDrop;
function boot(){const input=$('#searchInput');if(input){input.value='';input.setAttribute('autocomplete','off');input.setAttribute('name','case_search_query');input.setAttribute('data-form-type','other');}const fast=$('.fast-btn');if(fast)fast.onclick=window.fastOpenCase;document.addEventListener('click',e=>{const b=e.target.closest('.amount-btn');if(!b||!window.state)return;const n=Number(b.textContent);if(n>=1&&n<=10){window.state.openAmount=n;window.createRoulettes();window.updateOpenPrice?.();}});}
boot();
})();