(() => {
  'use strict';
  const ensure=(id,html)=>{let el=document.getElementById(id);if(el)return el;document.body.insertAdjacentHTML('beforeend',html);return document.getElementById(id);};
  ensure('profilePage',`<section class="profile-page" id="profilePage" style="display:none" aria-hidden="true"><div class="ed-page-head"><button class="back-btn" data-back>← Назад</button><button class="profile-settings-btn" data-route="/profile/settings" aria-label="Настройки"></button></div><div class="ed-profile-wrap"><div class="ed-profile-user"><div class="profile-avatar">👤</div><div><div class="profile-name" id="profileName">Гость</div><div class="settings-sub">Баланс: <strong><span id="profileBalance">0</span>₽</strong></div></div></div><div class="ed-profile-actions"><button class="profile-mini-btn" data-route="/upgrade">⬆️ Апгрейд</button><button class="profile-mini-btn" data-route="/profile/statistics">📊 Статистика</button><button class="profile-mini-btn" data-route="/profile/history">🕘 История</button><button class="profile-mini-btn danger" onclick="logout()">🚪 Выйти</button></div><div class="ed-section-title">Инвентарь</div><div class="profile-content"><div class="inventory-grid" id="inventoryGrid"></div></div></div></section>`);
  ensure('settingsOverlay',`<div class="settings-overlay" id="settingsOverlay" style="display:none"><div class="settings-box"><div class="settings-header"><div class="settings-title">Настройки</div><button class="settings-close" data-back>✕</button></div><div class="settings-list"><div class="settings-item-column"><div class="settings-name">Новый ник</div><input class="settings-input" id="newNickname" autocomplete="nickname" placeholder="Ник"><button class="settings-action-btn" onclick="changeNickname()">Сохранить</button></div><div class="settings-item-column"><div class="settings-name">Смена пароля</div><input class="settings-input" id="oldPassword" type="password" autocomplete="current-password" placeholder="Старый пароль"><input class="settings-input" id="newPasswordSettings" type="password" autocomplete="new-password" placeholder="Новый пароль"><button class="settings-action-btn" onclick="changePassword()">Изменить пароль</button></div><div class="settings-item ed-delete-row"><div><div class="settings-name red">Удалить аккаунт</div><div class="settings-sub">Действие нельзя отменить</div></div><button class="settings-action-btn delete-btn" onclick="deleteAccount()">Удалить</button></div></div></div></div>`);
  ensure('statsOverlay',`<div class="stats-overlay settings-overlay" id="statsOverlay" style="display:none"><div class="settings-box"><div class="settings-header"><div class="settings-title">Статистика</div><button class="settings-close" data-back>✕</button></div><div class="settings-list"><div class="settings-item"><span>Открыто кейсов</span><strong id="openedCases">0</strong></div><div class="settings-item"><span>Апгрейдов</span><strong id="upgradeCount">0</strong></div><div class="settings-item"><span>Потрачено</span><strong id="spentAmount">0₽</strong></div><div class="settings-item"><span>Получено</span><strong id="receivedAmount">0₽</strong></div><div class="settings-item"><span>Продано предметов</span><strong id="withdrawItems">0</strong></div><div class="settings-item best-drop-stat"><span>Лучший дроп</span><strong id="statsBestDrop">🏆 Нет дропа</strong></div></div></div></div>`);
  ensure('historyOverlay',`<div class="settings-overlay" id="historyOverlay" style="display:none"><div class="settings-box"><div class="settings-header"><div class="settings-title">История</div><button class="settings-close" data-back>✕</button></div><div class="settings-list" id="historyList"></div></div></div>`);
  [['ed-router-css','css/router.css?v=20260826e'],['ed-unified-css','css/unified.css?v=20260826e'],['ed-quality-css','css/quality-pass.css?v=20260826b'],['ed-final-fixes-css','css/site-fixes-20260826.css?v=2']].forEach(([id,href])=>{if(!document.getElementById(id)){const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=href;document.head.appendChild(l);}});
  const load=src=>{if(document.querySelector(`script[data-ed-src="${src}"]`))return;const s=document.createElement('script');s.src=src;s.dataset.edSrc=src;s.async=false;document.body.appendChild(s);};
  load('js/cloud-config.js?v=20260826b');load('js/router.js?v=20260826e');load('js/cloud-auth.js?v=20260826b');load('js/final-fixes.js?v=20260826e');load('js/quality-pass.js?v=20260826b');load('js/economy-sync.js?v=20260826b');load('js/site-fixes-20260826.js?v=2');
})();