(() => {
  'use strict';
  const ensure=(id,html)=>{let el=document.getElementById(id);if(el)return el;document.body.insertAdjacentHTML('beforeend',html);return document.getElementById(id)};
  ensure('profilePage',`<section class="profile-page" id="profilePage" style="display:none" aria-hidden="true"><div class="ed-page-head"><button class="profile-settings-btn" id="profileSettingsBtn" aria-label="Настройки">⚙</button><button class="back-btn" id="profileBackBtn" type="button">← Назад</button></div><div class="ed-profile-wrap"><div class="ed-profile-user"><div class="profile-avatar">👤</div><div><div class="profile-name" id="profileName">Гость</div><div class="settings-sub">Баланс: <strong><span id="profileBalance">0</span>₽</strong></div></div></div><div class="ed-profile-actions"><button type="button" class="profile-mini-btn" id="profileUpgradeBtn">⬆️ Апгрейд</button><button type="button" class="profile-mini-btn" id="profileStatsBtn">📊 Статистика</button><button type="button" class="profile-mini-btn" id="profileHistoryBtn">🕘 История</button><button type="button" class="profile-mini-btn danger" id="profileLogoutBtn">🚪 Выйти</button></div><div class="ed-section-title">Инвентарь</div><div class="profile-content"><div class="inventory-grid" id="inventoryGrid"></div></div></div></section>`);
  ensure('settingsOverlay',`<div class="settings-overlay" id="settingsOverlay" style="display:none" aria-hidden="true"><div class="settings-box"><div class="settings-header"><div class="settings-title">Настройки</div><button class="settings-close" id="settingsCloseBtn" type="button">✕</button></div><div class="settings-list"><div class="settings-item-column"><div class="settings-name">Новый ник</div><input class="settings-input" id="newNickname" autocomplete="nickname" placeholder="Ник"><button class="settings-action-btn" onclick="changeNickname()">Сохранить</button></div><div class="settings-item-column"><div class="settings-name">Смена пароля</div><input class="settings-input" id="oldPassword" type="password" autocomplete="current-password" placeholder="Старый пароль"><input class="settings-input" id="newPasswordSettings" type="password" autocomplete="new-password" placeholder="Новый пароль"><button class="settings-action-btn" onclick="changePassword()">Изменить пароль</button></div><div class="settings-item ed-delete-row"><div><div class="settings-name red">Удалить аккаунт</div><div class="settings-sub">Действие нельзя отменить</div></div><button class="settings-action-btn delete-btn" onclick="deleteAccount()">Удалить</button></div></div></div></div>`);
  ensure('statsOverlay',`<div class="stats-overlay settings-overlay" id="statsOverlay" style="display:none" aria-hidden="true"><div class="settings-box"><div class="settings-header"><div class="settings-title">Статистика</div><button class="settings-close" id="statsCloseBtn" type="button">✕</button></div><div class="settings-list"><div class="settings-item"><span>Открыто кейсов</span><strong id="openedCases">0</strong></div><div class="settings-item"><span>Апгрейдов</span><strong id="upgradeCount">0</strong></div><div class="settings-item"><span>Потрачено</span><strong id="spentAmount">0₽</strong></div><div class="settings-item"><span>Получено</span><strong id="receivedAmount">0₽</strong></div><div class="settings-item"><span>Продано предметов</span><strong id="withdrawItems">0</strong></div></div></div></div>`);
  ensure('historyOverlay',`<div class="settings-overlay" id="historyOverlay" style="display:none" aria-hidden="true"><div class="settings-box"><div class="settings-header"><div class="settings-title">История</div><button class="settings-close" id="historyCloseBtn" type="button">✕</button></div><div class="settings-list" id="historyList"></div></div></div>`);
  [['ed-unified-css','css/unified.css?v=20260826o'],['ed-final-fixes-css','css/site-fixes-20260826.css?v=20260826o']].forEach(([id,href])=>{if(!document.getElementById(id)){const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=href;document.head.appendChild(l)}});
  const bind=(id,fn)=>{const el=document.getElementById(id);if(!el||el.dataset.edBound)return;el.dataset.edBound='1';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();try{fn()}catch(err){console.error('[EmojiDrops]',id,err)}})};
  const wire=()=>{bind('profileSettingsBtn',()=>window.openSettings?.());bind('profileBackBtn',()=>window.closeProfile?.());bind('profileUpgradeBtn',()=>window.openUpgradeMenu?.());bind('profileStatsBtn',()=>window.openStats?.());bind('profileHistoryBtn',()=>window.openHistory?.());bind('profileLogoutBtn',()=>window.logout?.());bind('settingsCloseBtn',()=>window.closeSettings?.());bind('statsCloseBtn',()=>window.closeStats?.());bind('historyCloseBtn',()=>window.closeHistory?.())};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();