(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const money=v=>Number(String(v??0).replace(/[^0-9.,-]/g,'').replace(',','.'))||0;
  const color=i=>window.rarities?.[i?.rarity]?.color||'#ff7b00';
  let modal, selected=[], target=null, busy=false;
  function items(){return Object.values(window.cases||{}).flatMap(v=>Array.isArray(v)?v:[])}
  function open(){
    if(!window.state?.currentUser)return window.openAuth?.('login');
    if(modal)modal.remove(); selected=[];target=null;busy=false;
    modal=document.createElement('div');modal.id='safeUpgrade';
    modal.innerHTML=`<div class="su-box"><div class="su-head"><div><b>АПГРЕЙД</b><small>Выбери предметы и цель</small></div><button id="suClose">×</button></div><div class="su-grid"><div><h3>Инвентарь <span id="suCount">0</span></h3><div class="su-list" id="suInv"></div></div><div class="su-center"><div class="su-orb" id="suOrb">⬆️</div><strong id="suChance">Выбери цель</strong><button id="suRun" disabled>АПГРЕЙД</button></div><div><h3>Цель</h3><div class="su-list" id="suTargets"></div></div></div></div>`;
    document.body.appendChild(modal);injectStyle();
    $('suClose').onclick=close; modal.onclick=e=>{if(e.target===modal)close()};$('suRun').onclick=run;render();
  }
  function render(){const inv=$('suInv'),tg=$('suTargets');if(!inv)return;inv.innerHTML='';tg.innerHTML='';const inventory=window.state.currentUser.inventory||[];inventory.forEach((i,n)=>{const b=card(i,selected.includes(i));b.onclick=()=>{if(busy)return;const x=selected.indexOf(i);if(x>=0)selected.splice(x,1);else if(selected.length<6)selected.push(i);render()};inv.appendChild(b)});if(!inventory.length)inv.innerHTML='<span class="su-empty">Инвентарь пуст</span>';const seen=new Set();items().forEach(i=>{const k=`${i.emoji}|${i.price}|${i.rarity}`;if(seen.has(k))return;seen.add(k);const b=card(i,target===i);b.onclick=()=>{if(!busy){target=i;render()}};tg.appendChild(b)});const total=selected.reduce((s,i)=>s+money(i.price),0),goal=money(target?.price),chance=goal>total?Math.min(95,Math.max(1,total/goal*100)):0;$('suCount').textContent=selected.length;$('suChance').textContent=chance?`Шанс ${chance.toFixed(1)}%`:'Выбери цель';$('suRun').disabled=busy||!selected.length||!target||goal<=total;}
  function card(i,on){const b=document.createElement('button');b.className='su-card'+(on?' on':'');b.innerHTML=`<span style="color:${color(i)}">${i.emoji||'❔'}</span><small>${money(i.price)}₽</small>`;return b}
  async function run(){if(busy)return;const total=selected.reduce((s,i)=>s+money(i.price),0),goal=money(target?.price);if(!target||goal<=total)return;busy=true;render();$('suOrb').classList.add('spin');await new Promise(r=>setTimeout(r,900));const ok=Math.random()*100<Math.min(95,total/goal*100),u=window.state.currentUser;if(ok){const set=new Set(selected);u.inventory=(u.inventory||[]).filter(i=>!set.has(i));u.inventory.push({...target});window.state.balance=u.balance;window.saveUsers?.();window.renderInventory?.();window.updateBalanceUI?.();}$('suOrb').classList.remove('spin');$('suChance').textContent=ok?'УСПЕХ! 🎉':'НЕУДАЧА';busy=false;render();}
  function close(){modal?.remove();modal=null;selected=[];target=null;busy=false}
  function injectStyle(){if($('safeUpgradeStyle'))return;const s=document.createElement('style');s.id='safeUpgradeStyle';s.textContent=`#safeUpgrade{position:fixed;inset:0;z-index:20000;display:grid;place-items:center;background:rgba(5,6,8,.86);padding:16px}#safeUpgrade .su-box{width:min(1100px,96vw);max-height:92vh;overflow:auto;background:#111318;border:1px solid #34373d;border-radius:22px;padding:20px;color:#fff;box-shadow:0 25px 90px #000}.su-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #292c31;padding-bottom:14px}.su-head b{font-size:24px}.su-head small{display:block;color:#888;margin-top:5px}.su-head button{width:42px;height:42px;border:1px solid #34373d;border-radius:12px;background:#191b20;color:#fff;font-size:28px}.su-grid{display:grid;grid-template-columns:1fr 220px 1fr;gap:14px;margin-top:16px}.su-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(78px,1fr));gap:8px;max-height:55vh;overflow:auto}.su-card{min-height:82px;border:1px solid #292c31;border-radius:12px;background:#0d0f12;color:#fff;display:grid;place-items:center;cursor:pointer}.su-card span{font-size:34px}.su-card small{color:#aaa}.su-card.on{border-color:#ff7b00;box-shadow:0 0 18px #ff7b0025}.su-center{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px}.su-orb{width:150px;height:150px;border-radius:50%;display:grid;place-items:center;font-size:50px;border:4px solid #ff7b00;background:radial-gradient(circle,#29200f,#101216);box-shadow:0 0 45px #ff7b0035}.su-orb.spin{animation:suSpin .9s ease-in-out}.su-center button{width:100%;padding:13px;border:0;border-radius:10px;background:#ff7b00;font-weight:800}.su-center button:disabled{opacity:.35}@keyframes suSpin{to{transform:rotate(720deg)}}.su-empty{color:#777}@media(max-width:800px){.su-grid{grid-template-columns:1fr}.su-center{order:3}.su-list{max-height:230px}}
`;document.head.appendChild(s)}
  window.openUpgradeMenu=open;
})();