(()=>{'use strict';
const VERSION='20260901-1';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>`${Math.round(Number(n)||0)}₽`;
const rarityColor=r=>({common:'#9ca3af',rare:'#3b82f6',epic:'#a855f7',mythical:'#ef4444',legendary:'#ff8a00'}[r]||'#9ca3af');
const readUsers=()=>{try{const a=JSON.parse(localStorage.getItem('users')||'[]');return Array.isArray(a)?a:[]}catch{return[]}};
const current=()=>{const e=String(localStorage.getItem('currentUser')||'').toLowerCase();return readUsers().find(u=>String(u.email||'').toLowerCase()===e)||null};
const save=u=>{const a=readUsers(),i=a.findIndex(x=>String(x.email||'').toLowerCase()===String(u.email||'').toLowerCase());if(i>=0)a[i]=u;localStorage.setItem('users',JSON.stringify(a))};
function installStyle(){let s=q('#ed-ux-final-style');if(!s){s=document.createElement('style');s.id='ed-ux-final-style';document.head.appendChild(s)}s.textContent=`
/* One authoritative responsive layout */
html,body{width:100%!important;max-width:none!important;overflow-x:hidden!important}
main{width:100%!important;max-width:none!important;margin:0!important;padding:18px clamp(10px,2.2vw,42px) 142px!important}
.hero{display:none!important}
.home-divider{display:block!important;width:100%!important;height:2px!important;margin:0 0 18px!important;background:linear-gradient(90deg,transparent,#ff7b00 7%,#ff9a2e 50%,#ff7b00 93%,transparent)!important;border:0!important;box-shadow:0 0 14px #ff7b0040!important}
#cases,.cases{width:100%!important;max-width:none!important;display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:clamp(10px,1.25vw,22px)!important;margin:0!important;padding:0!important}
#cases .case-tile{width:100%!important;min-width:0!important;margin:0!important;padding:0!important}
#cases .case-card{width:100%!important;height:clamp(220px,16vw,310px)!important;min-height:220px!important;padding:clamp(12px,1.35vw,20px)!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:flex-start!important;border-radius:clamp(16px,1.4vw,24px)!important;contain:layout paint!important;backface-visibility:hidden!important;-webkit-backface-visibility:hidden!important;transform:translateZ(0);transition:transform .22s cubic-bezier(.22,1,.36,1),border-color .2s,box-shadow .2s!important}
#cases .case-card:hover{transform:translate3d(0,-4px,0)!important}
#cases .case-art{width:100%!important;height:clamp(78px,6.7vw,108px)!important;min-height:78px!important;flex:0 0 clamp(78px,6.7vw,108px)!important;font-size:clamp(54px,5vw,84px)!important;display:grid!important;place-items:center!important}
#cases .case-info{width:100%!important;min-width:0!important;flex:1!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:3px!important}
#cases .case-name{font-size:clamp(14px,1.3vw,22px)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;max-width:100%!important}
#cases .case-meta{font-size:clamp(10px,1vw,15px)!important}.case-price span{font-size:clamp(16px,1.3vw,22px)!important}
.live-section{position:fixed!important;left:0!important;right:0!important;bottom:0!important;width:100vw!important;max-width:none!important;margin:0!important;padding:8px clamp(10px,2.2vw,42px) calc(8px + env(safe-area-inset-bottom))!important;z-index:2147483000!important;box-sizing:border-box!important}
.live-title,.live-container{width:100%!important;max-width:none!important}.live-container{display:flex!important;overflow-x:auto!important;scrollbar-width:none!important}.live-container::-webkit-scrollbar{display:none}
/* Inventory */
.ed-sell-all{display:inline-flex;align-items:center;justify-content:center;margin:0 0 12px auto;padding:10px 14px;border:1px solid #ff7b00;border-radius:12px;background:#211306;color:#ff9d3d;font-weight:900;transition:transform .18s,background .18s}.ed-sell-all:hover{transform:translateY(-1px);background:#2c1909}.ed-sell-all:active{transform:scale(.98)}
/* Upgrade: static wheel + rotating pointer */
.final-upgrade{display:grid!important;grid-template-columns:minmax(0,1fr) 310px minmax(0,1fr)!important;gap:22px!important;align-items:start!important}
.final-wheel-col{display:flex!important;flex-direction:column!important;align-items:center!important;gap:8px!important}
.ed-wheel-shell{position:relative;width:250px;height:250px;display:grid;place-items:center;margin:2px auto 8px}
.ed-wheel{--chance:50%;--angle:0deg;width:216px;height:216px;border-radius:50%;position:relative;background:conic-gradient(#ff7b00 0 var(--chance),#202020 var(--chance) 100%);border:7px solid #2d2d2d;box-shadow:0 0 0 2px #ff7b0033,0 0 36px #ff7b0026,inset 0 0 30px #000;isolation:isolate}
.ed-wheel:before{content:'';position:absolute;inset:13px;border-radius:50%;border:1px dashed #ffffff25}.ed-wheel:after{content:'';position:absolute;inset:31px;border-radius:50%;background:#0e0e0e;border:1px solid #3b3b3b;box-shadow:inset 0 0 22px #000}
.ed-wheel-center{position:absolute;z-index:5;inset:50% auto auto 50%;transform:translate(-50%,-50%);width:70px;height:70px;border-radius:50%;display:grid;place-items:center;background:#111;border:2px solid #ff9a2e;color:#ff9a2e;font-size:24px;font-weight:1000;box-shadow:0 0 20px #ff7b0040}
.ed-wheel-win,.ed-wheel-lose{position:absolute;z-index:6;font-size:11px;font-weight:1000;letter-spacing:.12em;text-shadow:0 2px 5px #000}.ed-wheel-win{top:27px;left:50%;transform:translateX(-50%);color:#fff}.ed-wheel-lose{bottom:27px;left:50%;transform:translateX(-50%);color:#8b8b8b}
.ed-pointer-arm{position:absolute;left:50%;top:50%;width:3px;height:115px;transform-origin:50% 100%;transform:translate(-50%,-100%) rotate(var(--angle));z-index:8;will-change:transform}.ed-pointer-tip{position:absolute;top:-13px;left:50%;transform:translateX(-50%);width:0;height:0;border-left:11px solid transparent;border-right:11px solid transparent;border-top:24px solid #fff;filter:drop-shadow(0 0 7px #ff7b00)}
.ed-pointer-dot{position:absolute;bottom:-9px;left:50%;transform:translateX(-50%);width:11px;height:11px;border-radius:50%;background:#ff9a2e;box-shadow:0 0 14px #ff7b00}
.ed-wheel-chance{font-weight:1000;font-size:18px;color:#ff9d3d;text-align:center}.ed-wheel-caption{font-size:10px;color:#777;letter-spacing:.12em;text-transform:uppercase}
.ed-upgrade-result{margin:0 0 12px;padding:12px 14px;text-align:center;border-radius:13px;font-weight:1000;animation:edResult .35s cubic-bezier(.22,1,.36,1)}.ed-upgrade-result.ok{border:1px solid #3f8f4d;background:#142416;color:#9affaa}.ed-upgrade-result.no{border:1px solid #8f4141;background:#241313;color:#ffaaaa}@keyframes edResult{from{opacity:0;transform:translateY(-5px) scale(.97)}to{opacity:1;transform:none}}
@media(max-width:1100px){#cases,.cases{grid-template-columns:repeat(2,minmax(0,1fr))!important}.final-upgrade{grid-template-columns:1fr!important}.final-wheel-col{order:2}.final-upgrade>section:first-child{order:1}.final-upgrade>section:nth-child(3){order:3}.final-upgrade>.upgrade-submit{order:4}}
@media(max-width:600px){main{padding-left:7px!important;padding-right:7px!important;padding-bottom:122px!important}#cases,.cases{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.case-tile .case-card{height:clamp(182px,48vw,222px)!important;min-height:182px!important;padding:9px!important;border-radius:16px!important}.case-tile .case-art{height:clamp(58px,17vw,76px)!important;min-height:58px!important;flex-basis:clamp(58px,17vw,76px)!important;font-size:clamp(42px,12.5vw,58px)!important}.case-tile .case-name{font-size:clamp(13px,3.8vw,17px)!important}.case-tile .case-meta{font-size:10px!important}.case-price span{font-size:16px!important}.live-section{padding-left:7px!important;padding-right:7px!important}.ed-wheel-shell{width:210px;height:210px}.ed-wheel{width:182px;height:182px}.ed-pointer-arm{height:96px}.final-upgrade{gap:12px!important}}
@media(max-width:380px){#cases,.cases{gap:6px!important}.case-tile .case-card{height:180px!important;min-height:180px!important}.case-tile .case-art{font-size:45px!important}.case-tile .case-name{font-size:13px!important}.ed-wheel-shell{width:190px;height:190px}.ed-wheel{width:166px;height:166px}.ed-pointer-arm{height:87px}}
@media(prefers-reduced-motion:reduce){.case-card,.ed-pointer-arm,.ed-sell-all{transition:none!important;animation:none!important}}
`}
function ensureDivider(){const main=document.querySelector('main');if(!main)return;let d=main.querySelector('.home-divider');if(!d){d=document.createElement('div');d.className='home-divider';const cases=main.querySelector('#cases,.cases');if(cases)main.insertBefore(d,cases);else main.prepend(d)}}
function sellAll(){const u=current();if(!u||!Array.isArray(u.inventory)||!u.inventory.length)return;const total=u.inventory.reduce((s,x)=>s+(Number(x?.value)||Number(String(x?.price??0).replace(/[^0-9.]/g,''))||0),0);u.balance=(Number(u.balance)||0)+total;u.inventory=[];u.stats=u.stats||{};u.stats.received=(Number(u.stats.received)||0)+total;save(u);if(typeof window.renderInventory==='function')window.renderInventory();if(typeof window.syncBalance==='function')window.syncBalance()}
function inventoryButton(){const root=q('#inventory');if(!root)return;let b=root.parentElement?.querySelector('.ed-sell-all');if(!b){b=document.createElement('button');b.type='button';b.className='ed-sell-all';b.textContent='Продать всё';const title=root.parentElement?.querySelector('.section-title');(title?.parentElement||root.parentElement||root).insertBefore(b,title?.nextSibling||root)}b.disabled=!current()?.inventory?.length}
function upgradeMarkup(chance){const root=q('#finalWheel');if(!root)return;const p=root.parentElement;if(p?.querySelector('.ed-wheel'))return;const wrap=document.createElement('div');wrap.className='ed-wheel-shell';const w=document.createElement('div');w.className='ed-wheel';w.style.setProperty('--chance',`${Math.max(0,Math.min(95,chance*100))}%`);w.innerHTML='<div class="ed-wheel-win">УСПЕХ</div><div class="ed-wheel-lose">ПРОВАЛ</div><div class="ed-wheel-center">×</div><div class="ed-pointer-arm" style="--angle:0deg"><div class="ed-pointer-tip"></div><div class="ed-pointer-dot"></div></div>';wrap.appendChild(w);p.replaceChildren(wrap);}
function findUpgradeData(){const body=q('#upgradeModal .panel-body'),src=body?.querySelector('[data-final-source].selected'),tar=body?.querySelector('[data-final-target].selected'),mult=Number(body?.querySelector('[data-final-mult].active')?.dataset.finalMult||2);if(!src||!tar)return null;const users=current();const sourceIndex=Number(src.dataset.finalSource);const targetIndex=Number(tar.dataset.finalTarget);const source=users?.inventory?.[sourceIndex];const flat=Object.values(window.cases||{}).flat();const target=flat[targetIndex];return source&&target?{body,sourceIndex,targetIndex,source,target,mult}:null}
function animateUpgrade(){const data=findUpgradeData();if(!data)return;const chance=Math.min(.95,Math.max(.01,data.source.value*data.mult/data.target.value));upgradeMarkup(chance);const wheel=q('.ed-wheel',data.body);const arm=q('.ed-pointer-arm',wheel);if(!arm)return;const win=Math.random()<chance;const targetAngle=(win?(-90+Math.random()*Math.max(6,chance*75)):(90+(1-chance)*180+Math.random()*Math.max(6,(1-chance)*75)));wheel.style.setProperty('--chance',`${Math.round(chance*100)}%`);arm.style.transition='transform 2200ms cubic-bezier(.08,.78,.08,1)';arm.style.transform=`translate(-50%,-100%) rotate(${targetAngle+720}deg)`;setTimeout(()=>{const u=current();if(!u?.inventory?.[data.sourceIndex])return;const source=u.inventory[data.sourceIndex];if(!source||Number(source.value)!==Number(data.source.value))return;u.stats=u.stats||{};u.stats.upgrades=(Number(u.stats.upgrades)||0)+1;if(win){u.inventory[data.sourceIndex]={...data.target};u.stats.received=(Number(u.stats.received)||0)+Number(data.target.value||0);if(!u.bestDrop||Number(data.target.value)>Number(u.bestDrop.value||0))u.bestDrop={...data.target}}else u.inventory.splice(data.sourceIndex,1);save(u);if(typeof window.renderInventory==='function')window.renderInventory();if(typeof window.syncBalance==='function')window.syncBalance();const box=data.body;const result=document.createElement('div');result.className=`ed-upgrade-result ${win?'ok':'no'}`;result.textContent=win?`УСПЕХ · ${data.target.emoji}`:'ПРОВАЛ · Предмет потерян';box.prepend(result);setTimeout(()=>{if(typeof window.renderUpgrade==='function')window.renderUpgrade()},420)},2350)}
function bind(){window.addEventListener('click',e=>{const sell=e.target.closest('.ed-sell-all');if(sell){e.preventDefault();e.stopImmediatePropagation();sellAll();return}const submit=e.target.closest('#finalUpgradeSubmit');if(submit){e.preventDefault();e.stopImmediatePropagation();if(!submit.disabled)animateUpgrade();return}},true)}
function loop(){installStyle();ensureDivider();inventoryButton();const modal=q('#upgradeModal');if(modal?.classList.contains('show')){const data=findUpgradeData();if(data){const chance=Math.min(.95,Math.max(.01,data.source.value*data.mult/data.target.value));upgradeMarkup(chance)}}}
function boot(){bind();loop();let timer=0;const tick=()=>{cancelAnimationFrame(timer);timer=requestAnimationFrame(()=>{loop()})};new MutationObserver(tick).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','data-final-source','data-final-target','data-final-mult']});window.addEventListener('load',loop,{once:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();