(()=>{'use strict';if(window.__edUXFinalV5)return;window.__edUXFinalV5=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const prices={transport:25,animals:40,food:60,nature:85,moves:110,smile:140,sport:180,games:230,space:290,ocean:360,flags:420,music:160};
const money=n=>`${Math.round(Number(n)||0)}₽`;
const readUsers=()=>{try{const a=JSON.parse(localStorage.getItem('users')||'[]');return Array.isArray(a)?a:[]}catch{return[]}};
const current=()=>{const e=String(localStorage.getItem('currentUser')||'').toLowerCase();return readUsers().find(u=>String(u.email||'').toLowerCase()===e)||null};
const saveUser=u=>{const a=readUsers(),i=a.findIndex(x=>String(x.email||'').toLowerCase()===String(u.email||'').toLowerCase());if(i<0)return false;a[i]=u;localStorage.setItem('users',JSON.stringify(a));return true};
function addSellAll(){const root=$('#inventory');if(!root)return;const host=root.closest('.panel-body')||root.parentElement||root;let b=$('.ed-sell-all',host);if(!b){b=document.createElement('button');b.type='button';b.className='ed-sell-all';b.textContent='Продать всё';const title=$('.section-title',host);(title||root).insertAdjacentElement(title?'afterend':'beforebegin',b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const u=current();if(!u||!Array.isArray(u.inventory)||!u.inventory.length)return;const total=u.inventory.reduce((s,x)=>s+(Number(x?.value)||Number(String(x?.price||'').replace(/[^0-9.-]/g,''))||0),0);u.balance=Math.round((Number(u.balance)||0)+total);u.inventory=[];saveUser(u);window.renderInventory?.();window.syncBalance?.();setTimeout(addSellAll,0)})}b.disabled=!current()?.inventory?.length}
function fixCaseButtons(){const u=current(),balance=Number(u?.balance)||0;$$('[data-case]').forEach(b=>{const key=b.dataset.case;if(!prices[key])return;const blocked=balance<prices[key];b.disabled=blocked;b.classList.toggle('ed-insufficient',blocked)});$$('.open-cost').forEach(el=>{const modal=el.closest('.modal,.panel');if(!modal)return;const text=modal.textContent||'';const m=text.match(/(\d+)₽/);const p=m?Number(m[1]):0;if(p&&balance<p){modal.querySelectorAll('.amounts,.open-cost').forEach(x=>x.style.display='none');modal.querySelectorAll('button').forEach(b=>{if(/откры|open/i.test(b.textContent||'')){b.disabled=true;b.classList.add('ed-insufficient')}})}})}
function addWheel(){const marker=$('#finalWheel');if(!marker||marker.dataset.v5)return;marker.dataset.v5='1';marker.innerHTML=`<div class="ed-wheel-shell"><div class="ed-wheel"><div class="ed-wheel-mark">UPGRADE</div><div class="ed-wheel-label">×</div><div class="ed-pointer"><div class="ed-pointer-center"></div></div></div><div class="ed-chance"><span>WIN · выбранный шанс</span><span>MISS · остальное поле</span></div></div>`}
function boot(){addSellAll();fixCaseButtons();addWheel();window.addEventListener('load',()=>{addSellAll();fixCaseButtons();addWheel()},{once:true});document.addEventListener('click',e=>{if(e.target.closest('#cases,[data-case]'))setTimeout(fixCaseButtons,0);if(e.target.closest('#inventory'))setTimeout(addSellAll,0);if(e.target.closest('[data-upgrade],#upgradeModal,.upgrade-item,.upgrade-target'))setTimeout(addWheel,0)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();